### ISSUE TITLE
Feature request: Option to use other division

### ISSUE THREAD

**Issue by infeeeee** [Fmstrat/wintile#1]
Thank you for the extension, works perfectly, I really like it. 

I use an ultrawide monitor, and it wood be nice if the windows could be sized to 1/6 instead of 1/4. So 3 columns, 2 rows.

**Comment by Fmstrat** [comment]
I actually just mentioned this in another issue. This is on the TODO.

**Comment by Fmstrat** [comment]
@infeeeee I've got support in develop for 2 or 4 column (once I build the config options). Does 4 column meet the needs of this issue?

**Comment by Fmstrat** [comment]
@infeeeee Nevermind, I added 3 column support in `develop` for the next release. This will be changed in the new settings screen.

**Comment by infeeeee** [comment]
Yes, the best is an option for this, thank you!
