### ISSUE TITLE
Fix for flashing windows breaks mouse resize

### ISSUE THREAD

**Issue by Fmstrat** [Fmstrat/wintile#10]
When mousing out of a maximize state, the window keeps it's size vs restoring to original or default. Need to track mouse state to fix.

Linked to: https://github.com/Fmstrat/wintile/issues/5

**Comment by Fmstrat** [comment]
@ba32107 Any interest in taking this on?

**Comment by ba32107** [comment]
Ouch, yes, this is an oversight, I will look into it whenever I can.

**Comment by Fmstrat** [comment]
I now also recall why I used the maximize function. Terminal windows, or other windows that only support window resizing as a multiple of their font size won't take up the full screen unless maximize mode is turned on.

**Comment by ba32107** [comment]
Yes, I noticed this as well. I decided that for me personally, the benefit of the snappy window movement was worth losing a little bit of cosmetics. 

I also did another improvement in my own fork, I will raise an issue here to get your opinion. 

And I will definitely look into this problem with the mouse (I'm hoping to do it over the weekend).

**Comment by Fmstrat** [comment]
Awesome, thanks. The `develop` branch is non functioning at the moment, so you may need to work against a previous revision. I'm adding in a configurable grid to support ultrawide monitors in that branch and only about 85% done.

**Comment by Fmstrat** [comment]
`develop` is function now. Including a config for 8 tile mode and top/bottom half support. Just going to do some other tweaks before working on the config, but it should be good for any mouse work now.

**Comment by Fmstrat** [comment]
Sorry for flooding the issue, but want to make sure you know the setting exists. There is now a `config.useMaximize` which allows use of vertical/horizontal maximization as a toggle.

**Comment by Fmstrat** [comment]
Fixed in `develop`

**Comment by Fmstrat** [comment]
`grap-op-begin` occurs on window alt-tab as well as mouse grab. Need to check for actual window movement.

**Comment by Fmstrat** [comment]
Well nevermind, that was much easier than expected.

**Comment by ba32107** [comment]
I just had a chance to look into this. Tried the new develop branch, it's really sleek! I have a few suggestions / bug fixes / etc. I will open issues and pull requests for each.
