### ISSUE TITLE
Limit use of global scope and depricate Tweener

### ISSUE THREAD

**Issue by Fmstrat** [Fmstrat/wintile#102]
From GNOME Extensions review. This was feedback on the diff between v7 and v8: https://github.com/Fmstrat/wintile/compare/v7...v8

What spare time I've had I've been focusing on `samba-domain`, so if @rsxchin or @phavekes have time, please let me know here you're jumping in.

```
1. You cannot create objects in global scope which is the same as init:
    - line 43-52 extension.js
    - line 16-24 prefs.js
    https://gjs.guide/extensions/review-guidelines/review-guidelines.html#only-use-init-for-initialization

2. That's too much for global scope:
    
    - line 66 extension.js
    - line 69 extension.js
    - line 726-730 extension.js
    
    https://gjs.guide/extensions/review-guidelines/review-guidelines.html#only-use-init-for-initialization

3. Remove timeout on disable (line 643, 651, 674, 694, 859, 898 extension.js):
    https://gjs.guide/extensions/review-guidelines/review-guidelines.html#remove-main-loop-sources

4. `Tweener` is a deprecated module. Please remove it for the next version.
    You can use `ease()` instead. For example:

    ```js
    widget.ease({    
        x: newX,
        y: 10,
        opacity: 100,
        duration: 2000,
        mode: Clutter.AnimationMode.EASE_OUT_BOUNCE,
        onComplete: () => {
            log('Animation is finished');
        }
    });
    ```

5. Remove line 926 (extension.js) if condition.
    You should disconnect those signals without being dependent on other condition.
    Also null out those signal id holders in disable (`onWindowGrabBegin` and `onWindowGrabEnd`).

If you need any help with your extension you can ask us on:
- [GNOME Matrix Channel](https://matrix.to/#/#extensions:gnome.org)
- IRC Bridge: irc://irc.gimpnet.org/shell-extensions
```

Related to: https://github.com/Fmstrat/wintile/issues/99

**Comment by rsxchin** [comment]
1. ?
2. ?
3. ?
4. ?
5. #104

**Comment by rsxchin** [comment]
Do you want me to go ahead and merge what I want, or do I need it to be tested by either of you?

**Comment by rsxchin** [comment]
#106 is the last one to be merged. I'd like it if someone looked at it.

**Comment by rsxchin** [comment]
All items have been completed and merged.  They work on my end.
