### ISSUE TITLE
[develop] Preview settings are not straightforward

### ISSUE THREAD

**Issue by ba32107** [Fmstrat/wintile#12]
In the new settings panel, `Turn on mouse dragging support` is a bit misleading - I assumed it would snap the window into the grid as I was dragging the window. Turns out it's actually the preview. Additionally, the `Use double width...` setting is only relevant when the preview is enabled.

My suggestions:
 * Rename `Turn on mouse dragging support` to `Enable preview while dragging windows`
 * Move the `Use double width...` setting under the preview setting and indent it a bit
 * The above setting should only be active if the preview setting is enabled

I will look into this whenever I have some more time.

**Comment by Fmstrat** [comment]
Hi, I just want to confirm your expectations of the mouse dragging support. If mouse dragging is enabled, it shows the preview on drag, and snaps on release. If mouse dragging is disabled, neither of those occur, so it's not just the preview.  I do agree the double width should be moved as a sub-setting, good idea!

**Comment by Fmstrat** [comment]
This is merged, and then I added another commit to clarify "snapping"
