### ISSUE TITLE
v10.1 should be sent up

### ISSUE THREAD

**Issue by GrylledCheez** [Fmstrat/wintile#126]
@Fmstrat, there was a regression in v10 that took out some important code by @phavekes

We re-added it and set a new release of v10.1 if you wanted to send that to gnome. Otherwise check PR #124 for v11

**Comment by Fmstrat** [comment]
@GrylledCheez If 11 is already ready for merge, I'll give that one a shot today on my systems so we can make the jump. Thank you!

**Comment by Fmstrat** [comment]
You could also clone directly into the `extensions` folder, and run `build.sh` and be done. This way you can do a `git pull` to get the latest version in the future. That being said, given the great work of contributors we should have a new version out soon.

**Comment by GrylledCheez** [comment]
Just make sure you "git checkout develop" before you build. That way you'll be in bleeding edge :D

**Comment by GrylledCheez** [comment]
> You brave soul.


I stand by my edits

**Comment by Fmstrat** [comment]
@GrylledCheez `develop` won't activate for me. `master` seems to work fine, however. I'm running X11 and GNOME shell version 3.36 in Ubuntu 20.04. Any thoughts before I try to debug?

Note: I also reset the column default to 2 in `develop`. Since existing users have that as default, changing to 3 if they've never updated that setting will force them into 3 column mode unexpectedly.

**Comment by GrylledCheez** [comment]
And you ran build.sh before you started? 
Does it look activated on the tweak tool? Did you make sure that the extension-updates folder was empty? If not then it will be "updated" when you restart the session.

**Comment by Fmstrat** [comment]
Yea looks like `log` was switched for `console.log`, which doesn't exist in 3.36 (Ubuntu 20.04). Glad I still haven't upgraded.

**Comment by Fmstrat** [comment]
Ok, only thing I found in `develop` was when using arrow keys if you're in an upper/lower corner and try to go farther it jumps to 100% height, but that's fine to me. Any cleanup required before a master merge?

**Comment by GrylledCheez** [comment]
Go ahead and give the _log function an if else to use console.log or global.log or I can do it in a bit

**Comment by GrylledCheez** [comment]
@Fmstrat. Ready to merge when you are. Just need approval

**Comment by GrylledCheez** [comment]
> Ok, only thing I found in `develop` was when using arrow keys if you're in an upper/lower corner and try to go farther it jumps to 100% height, but that's fine to me. Any cleanup required before a master merge?

No further cleanup required. Go ahead and approve the pull-request. Thanks for letting me be a part of this.
