### ISSUE TITLE
Broken stuff that's broken in WinTile, but was fixed in WinTile Reloaded (glitchy snapping to bottom corners with 100ms delay)

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [Fmstrat/wintile#128]
I'm fixing up my instructions here: https://askubuntu.com/a/1446690/327339. 

I see WinTile Reloaded is unfortunately deleted: https://github.com/Captn138/wintile-reloaded

And WinTile still has some bugs that were fixed in WinTile Reloaded. One is this: change `Delay in ms before preview displays` from 500ms to 100ms. This worked fine in WinTile Reloaded, but in WinTile tag `v10.1`, it is *super glitchy* when you snap to a bottom-left or bottom-right corner. Note: my columns is set to 2.

I installed v10.1 per my instructions above. Namely: 

```bash
cd ~/.local/share/gnome-shell/extensions
# clone the tool
git clone https://github.com/Fmstrat/wintile
cd wintile
# Check out the tag of the latest release from here:
# https://github.com/Fmstrat/wintile/releases
git checkout v10.1  # update this to the latest released version
# build it
./build.sh
# extract the zip file up one level, into the
# `~/.local/share/gnome-shell/extensions/` dir
unzip wintile@nowsci.com.zip -d ../wintile@nowsci.com

# log out of Ubuntu
gnome-session-quit
```

Log back in and activate WinTile via your Gnome Extension Manager (sudo apt install gnome-shell-extension-manager).

**Comment by ElectricRCAircraftGuy** [comment]
Possibly related? https://github.com/Fmstrat/wintile/issues/126

**Comment by GrylledCheez** [comment]
Do you have the same issues with the develop branch? That's the v11 in progress

**Comment by ElectricRCAircraftGuy** [comment]
The version tagged v10.1 is the v11 in progress?

**Comment by ElectricRCAircraftGuy** [comment]
note: anything < 275 ms causes the glitches.

**Comment by ElectricRCAircraftGuy** [comment]
I just redid my installation steps on branch `develop` at commit `311fc16677b6b3a5d82cfb4840bd7584caa1b070`, and yes, the glitching is still present. 

Meanwhile, I'm starting a new job and just need my setup to work. I'm going to restore WinTile Reloaded as my own repo, and point my instructions to that. When you get your fixes all in, please let me know and I can update my instructions on Ask Ubuntu accordingly.

**Comment by GrylledCheez** [comment]
Can you describe the glitch? Can you go into the settings and see if the ultrawide-only mode is there? If it's not then you are using the wrong version. Also, are you using Xorg or Wayland?

**Comment by GrylledCheez** [comment]
@ElectricRCAircraftGuy, okay. Now that I'm at my computer I can see what you're talking about. I'll see what I can do to make it not do that stutter thing. If not, we might just increase the lower bounds.

**Comment by ElectricRCAircraftGuy** [comment]
The glitch is where it continually shows the resizing animation like 20x per second. Sounds like you can see it now. I was going to make a video of it. If you still need that, let me know. 

I brought WinTile Reloaded back: https://github.com/ElectricRCAircraftGuy/wintile-reloaded

It works perfectly. You might use `meld` to do a side-by-side comparison or something, or look at the commit history, to see what the differences are and why it works perfectly but yours doesn't. To see commits that are in `branch1` but not `branch2`, for instance, do this:

```bash
git log branch1 ^branch2
```

That may allow you to see which commits differ too. 

>  Can you go into the settings and see if the ultrawide-only mode is there? If it's not then you are using the wrong version. Also, are you using Xorg or Wayland?

What ultrawide mode? Am I missing something? Here's what I see, including the `Treat monitors <= 16:9 as 2x2` setting:

![image](https://github.com/Fmstrat/wintile/assets/6842199/b3c8e1c2-8691-423a-bc58-9fa82260cb3f)

I'm using Wayland. On WinTile Reloaded though, I've extensively used Wayland and X11, and both window managers work *perfectly* with that tool. I've never had WinTile work as well as WinTile Reloaded yet, and I've been using WinTile Reloaded daily now since Dec. 2022.

**Comment by GrylledCheez** [comment]
While I'm figuring out how to do these timers better, would you mind setting it back to 500 ms and playing around?  The <= 16:9 setting is the ultra-wide only.  It lets me have 4x2 on my ultrawide while leaving my laptop as 2x2.

I'm interested in your thoughts on the center bottom of each column spawning at max height.

**Comment by ElectricRCAircraftGuy** [comment]
What does <= 16:9 mean? Are you considering it a division problem? So, 16/10 < 16/9 < 16/8?

I have a 16/10 on one laptop, which is < 16/9, and 16/9 on another laptop. And I have a 16/9 4k 32" curved monitor (the same as 4 of my 16/9 laptop screens all in one), and an old 5:4 external monitor. I don't have a widescreen monitor--the closest to it would be my 3840x2160 16:9 4K 32" monitor.

**Comment by GrylledCheez** [comment]
> What does <= 16:9 mean? Are you considering it a division problem? So, 16/10 < 16/9 < 16/8?
16:9 is about 1.78
16:10 is exactly 1.6
But because screen size is being reported as available screen I stead of total screen, I just check if the ratio is less than 1.9

How would you personally word the setting?

**Comment by GrylledCheez** [comment]
@ElectricRCAircraftGuy,try out 1e5ba8313d9f1a11212521d14c7becab2002a0aa on the remove_stutter branch.

**Comment by GrylledCheez** [comment]
@ElectricRCAircraftGuy, I found a more reliable way with this c13430963bae59b74b5aece4b95339893ad14531

**Comment by GrylledCheez** [comment]
fixed in #129 (in develop)

Thanks for getting me to do it.  Give me ANY more bugs you find or any feature suggestions. The dopamine hit was fire

**Comment by GrylledCheez** [comment]
@ElectricRCAircraftGuy, just checking in and seeing if the newly released v11 master works for you.

**Comment by ElectricRCAircraftGuy** [comment]
@GrylledCheez , hi, I really appreciate you making these fixes and making and supporting this too. Unfortunately, I haven't been able to try out your v11 master yet. I [just started a new job](https://www.linkedin.com/feed/update/urn:li:activity:7072445075485519872/) and have been travelling for 2 weeks for it too.

**Comment by ElectricRCAircraftGuy** [comment]
I think it would make the most sense if I could try it once Gnome Extensions hosts your latest release with the fix, so I can easily get it without the extra clone and build steps. When will your latest release with the fixes be released to the Gnome Extensions store thing?

**Comment by GrylledCheez** [comment]
Yeas, but only @Fmstrat knows how long that takes. You only need to do the build steps 1 time though. I DON'T suggest cloning the git repo directly to your extensions folder, because gnome will overwrite it if/when it gets updated at gnome.org

**Comment by Fmstrat** [comment]
It's on my calendar for the morning before I'm off work tomorrow, so however long GNOME takes after that.

**Comment by GrylledCheez** [comment]
@Fmstrat, did they ever give any feedback on v10, or did we release v11 too fast for you to submit it?

**Comment by GrylledCheez** [comment]
@Fmstrat were you able to get it sent out?

**Comment by GrylledCheez** [comment]
@ElectricRCAircraftGuy, have you tried out the latest develop or master branches?  I hope you like what I've done.

**Comment by GrylledCheez** [comment]
@ElectricRCAircraftGuy, we published v12 on EGO! Open any new issues you find.

**Comment by ElectricRCAircraftGuy** [comment]
> @ElectricRCAircraftGuy, we published v12 on EGO! Open any new issues you find.

@GrylledCheez , thanks for your work on this! Now that you've gotten the change pushed up to Gnome Extensions, I've just changed to the latest WinTile version provided by them here: https://extensions.gnome.org/extension/1723/wintile-windows-10-window-tiling-for-gnome/, and it seems to work great! Thanks again. I'll open up issues if I have any more problems in the future.

**Comment by ElectricRCAircraftGuy** [comment]
@GrylledCheez , what does EGO stand for, by the way?

**Comment by ElectricRCAircraftGuy** [comment]
@GrylledCheez , with your fix in place and working, and the fix released to Gnome Extensions, I have updated my answer here: [Ask Ubuntu: How can I automatically resize a window to 1/4 of the screen and snap it to a corner in Ubuntu 22.04?](https://askubuntu.com/a/1446690/327339)

**Comment by GrylledCheez** [comment]
> @GrylledCheez , what does EGO stand for, by the way?

Extensions.Gnome.Org
