### ISSUE TITLE
[develop] Bug: up-down corner behavior inconsistent in 4 column mode

### ISSUE THREAD

**Issue by ba32107** [Fmstrat/wintile#13]
When moving the window in the corner from bottom to top, the behavior is not the same as all other cases.

Repro steps:
 * Set 4 column mode
 * Move a window in the top left corner
 * Move down, and the window expands vertically (as expected)
 * Move down, and the window goes into the bottom left corner (as expected)
 * Now move up, and observe that the window goes straight up. The expected behavior would be to expand vertically again. 

This also happens on the right side. Works correctly in 2 / 3 column mode.

**Comment by Fmstrat** [comment]
Thanks for all the reviews/reports!

This is a great catch. I'll get on a fix for it.

**Comment by Fmstrat** [comment]
Fixed in https://github.com/Fmstrat/wintile/commit/71c8955d39dad571e00945d5e5801b58d9e807ab
