### ISSUE TITLE
Enable Discussion Space

### ISSUE THREAD

**Issue by oenu** [Fmstrat/wintile#135]
Would be good to be able to talk with other contributors, any interest in either a github discussion space or a discord/matrix/irc?

Eg. Is there interest in porting to typescript?

**Comment by GrylledCheez** [comment]
Gnome extensions are written in Gnomes own Gnome Javascript (GJS). Unless you're wanting it in other platforms or something?

**Comment by GrylledCheez** [comment]
I personally think that this repo doesn't lend well to discussions and is better being issue driven. 

@Fmstrat, do you want to turn on discussions for the repo?

**Comment by GrylledCheez** [comment]
@oenu were there any suggestions or questions you have right now?

**Comment by oenu** [comment]
Main suggestion is to implement some kind of expanding thirds (if it doesnt exist already). I had been using https://github.com/rxhanson/Rectangle but its macos only. 
best feature would be quick keybinds to move windows to 1/3 2/3rds.

Hotkeys:
E - T (left two thirds and right two thirds)
D F G (thirds from left to right)

Really makes it easy to quickly throw windows around and is very texturally pleasing to have a key representation of the screens on the monitor

**Comment by oenu** [comment]
> Gnome extensions are written in Gnomes own Gnome Javascript (GJS). Unless you're wanting it in other platforms or something?

Also re: this, you are correct I saw javascript and had an instinctual response to type it up as a web dev, will look into gnomejs to possibly implement above suggestion

**Comment by GrylledCheez** [comment]
The simplest way to get 2 cols with 3 Col is to super+up then super the direction to shrink. It's best not to interfere with too many other established hot keys.

**Comment by Fmstrat** [comment]
> I personally think that this repo doesn't lend well to discussions and is better being issue driven.
> 
> @Fmstrat, do you want to turn on discussions for the repo?

Totally agree, with work these days I can barely keep up with the crazy-fast work @GrylledCheez is doing. I'll be more attentive now, but I don't think we'll be providing support-based discussion for this one. @GrylledCheez feel free to close if you agree.

**Comment by GrylledCheez** [comment]
@Fmstrat, I'm willing to try discussions out at least as a trial.

**Comment by GrylledCheez** [comment]
I can't enable them because I'm only a collaborator. Only maintainers can change things like that.
