### ISSUE TITLE
v11.1 Requirements 

### ISSUE THREAD

**Issue by Fmstrat** [Fmstrat/wintile#137]
@GrylledCheez so close. We will need to be careful with number 2 to make sure we keep 3.36 and only remove before so we don't break Ubuntu 20.04. v11 rejections:

1. Rejected because `disable` won&#x27;t getting called in prefs.js (line 36).

   Just create `gsettings` inside `buildPrefsWidget` and;

   attach it to the prefs widget to avoid garbage collecting before window close:

    ```js

   const gsettings = ExtensionUtils.getSettings();

   layout._gsettings = gsettings;

   ```

2. You can remove older than 3.36 and

   use `ExtensionUtils.getSettings()` instead of line [1188-1190](tel:1188-1190) (extension.js), 22-30 (prefs.js).

**Comment by GrylledCheez** [comment]
Did you want to merely patch a v11.1 directly into master real quick? I'm out with the family at the moment. We can cherrypick into develop it after it gets accepted.

**Comment by GrylledCheez** [comment]
For the 2nd one, I suggest doing the version check and defining it dynamically.

**Comment by GrylledCheez** [comment]
partially done with this. I should be done in about hours and then I'll send it off to @phavekes to check on his gnome 3 system

**Comment by GrylledCheez** [comment]
@Fmstrat, do you think they'll have a problem because we didn't deprecate < 20.04? (< 3.36)

**Comment by GrylledCheez** [comment]
Just close this when it's submitted.

**Comment by GrylledCheez** [comment]
After re-reading the requirements, I'm closing this in favor of #140
