### ISSUE TITLE
[develop] Bug: applications that start maximized are minimzed on down

### ISSUE THREAD

**Issue by ba32107** [Fmstrat/wintile#14]
When an application starts maximized, and I move down, the window is minimized immediately. I would expect the window to unmaximize. Since the window started maximimized, there is no previous position, so a default unmaximized size could be calculated (e.g. a fixed padding from each side).

**Comment by Fmstrat** [comment]
Fixed in https://github.com/Fmstrat/wintile/commit/fee067fd8c696123ced28cf36fb3bcfe668581b0
