### ISSUE TITLE
v12 ready for gnome review. someone tell @Fmstrat

### ISSUE THREAD

**Issue by GrylledCheez** [Fmstrat/wintile#149]
supercedes #143

**Comment by GrylledCheez** [comment]
@phavekes and @Fmstrat, how come neither of you told me I was numbering releases incorrectly?

**Comment by GrylledCheez** [comment]
The prefs.js and the compiled schemas got removed from your v11 submission on EGO somehow. They're waiting on you to say "no, I didn't remove them on purpose".

**Comment by GrylledCheez** [comment]
@Fmstrat 
The prefs.js and the compiled schemas got removed from your v11 submission on EGO somehow. They're waiting on you to say "no, I didn't remove them on purpose".

**Comment by Fmstrat** [comment]
I just saw that and updated accordingly. Thanks!

**Comment by GrylledCheez** [comment]
24 hours after release, and we're at 4,687 downloads!!!
