### ISSUE TITLE
renumber tags and releases after 7

### ISSUE THREAD

**Issue by GrylledCheez** [Fmstrat/wintile#151]
EGO increments versions when extensions are accepted. 

So once the next iteration published, that should either be tagged as v8, or have a new tag system such as "EGO-v8".

**Comment by Fmstrat** [comment]
The latest release going through GNOME Extensions is 12 (there was an errant `master.gitignore` file in and `prefs.js` was missing from the zip so it needed re-submission. At that point, we'll be level with the currently listed version.

Perhaps we should consider separating the GitHub versions from the GE versions? I.E. on next release start with `vYYYY.MM.DD-1` such as `v2023.07.03-1` as the tag, and then in the release title we can include both that and the GE version once they approve, so the title would be `v2023.07.03-1 - GE v13`. Thoughts?

**Comment by GrylledCheez** [comment]
I like the dated tags idea. And luckily

I don't know how the files were missing. I just pulled them all down and checked them out. None of them had a `master.gitignore` and they all had `prefs.js`

Maybe we shouldn't make a release tag until they accept?

I also remade the `build.sh` to only include required files as well as compile the schemas.

**Comment by Fmstrat** [comment]
Accepted! Finally ;) And great idea with `build.sh`.

**Comment by Fmstrat** [comment]
Alright, latest release is named `v2023.07.03-1 (GE v12)` and has a tag of `v2023.07.03-1` and a tag of `v12`.

When releases happen on GitHub, we can use the name and tag of `vYYYY.MM.DD-#` (The # for if more than one happen in a day), and whenever GNOME accepts, I can add the `v##` tag and `(GE v##)` element of the title.
