### ISSUE TITLE
Change shells on EGO 

### ISSUE THREAD

**Issue by GrylledCheez** [Fmstrat/wintile#152]
@Fmstrat, can you change 40.0 into 40 in v7 on EGO without it needing to be a full new submission? It's the only one that says 40.0

![Screenshot_20230703_141659_Chrome](https://github.com/Fmstrat/wintile/assets/68041324/d795f0a5-e996-43a7-a7ef-c673d2da5682)

**Comment by Fmstrat** [comment]
Unfortunately no, there's no way to edit previous versions :(

**Comment by Fmstrat** [comment]
Actually... I could inactivate v7.. I wonder what the consequences of that is.

**Comment by GrylledCheez** [comment]
I just asked in ego's matrix chat if they could do it. We'll see what they say. Because we don't want to accidentally deprecate it for the older shell users.

**Comment by GrylledCheez** [comment]
JustPerfection just confirmed no edits are possible by anyone. So inactivating it is the only option other than ignoring it.
