### ISSUE TITLE
V2023.07.10-1 ready for EGO 

### ISSUE THREAD

**Issue by GrylledCheez** [Fmstrat/wintile#154]
@Fmstrat, the latest zip was built with the latest build.sh

**Comment by GrylledCheez** [comment]
@Fmstrat, I forgot to ask you before. Did you mute this repo when we were doing lint testing?

**Comment by Fmstrat** [comment]
Doh, yea I filtered it to a folder. I'll turn that off, but mostly it's just really busy work right now.

**Comment by GrylledCheez** [comment]
EGO accepted without the changes.  Rolling them into next release

**Comment by GrylledCheez** [comment]
Well that's frustrating. At this point in the last release cycle (48 hours), we were at 6k downloads. This time we haven't hit 2k.
