### ISSUE TITLE
Ready for EGO release

### ISSUE THREAD

**Issue by GrylledCheez** [Fmstrat/wintile#159]
1. Updated metadata.json to include ctrl features
2. Fixed bug manually moving tiles from big screens to small screens
3. Removed code that EGO didn't like
5. added 1 col mode and 5 row mode by request
5. Screens in Portrait mode will automatically switch column and row values.
      Example:
      You have 2 ultrawide monitors, one is landscape, the other is portrait.
      Your config is set to 5 columns and 2 rows.
      The landscape screen with have 5 columns and 2 rows.
      The portrait screen with have 5 rows and 2 columns.

**Comment by GrylledCheez** [comment]
@Fmstrat, bump

**Comment by GrylledCheez** [comment]
I lied. You have to accept pull request #161 first.

**Comment by GrylledCheez** [comment]
@Fmstrat, I see you're still making more repost. Are you abandoning this one?

**Comment by Fmstrat** [comment]
Released as v14 (that was quick this time).
