### ISSUE TITLE
Portrait mode displays not supported

### ISSUE THREAD

**Issue by skewty** [Fmstrat/wintile#160]
My 4k in portrait mode does not appear to be properly supported.
I cannot, for example, get the target coloring to appear anywhere on the bottom.

My display configuration is:

- Primary: 3840x1600 to the left
- Secondary (extended): 3840x2160 @ 150% to the right in portrait

I am expecting my primary to be detected as an ultra-wide and my 4k to be detected as a non-ultra-wide.

My configuration is as follows:

- Number of columns: 3
- Number of rows: 2
- Use different rows and columsn for non-ultrawide monitors: enabled
- Number of columns for non-ultrawide: 2 (I cannot set 1 for some reason -- upon exiting it doesn't save)
- Number of rows for non-ultrawide: 2

**Comment by GrylledCheez** [comment]
I think I see the issue. My current calculation for if it's an ultrawide is checking of width/height is grrater than 1.9

If it's in portrait mode, how many rows/columns MAX do you think it should have?

**Comment by GrylledCheez** [comment]
@skewty, are you able to drop tiles with ctrl+drag and ctrl+super+drag?

**Comment by skewty** [comment]
On the primary landscape monitor everything works but on the portrait monitor I can drop tiles using Ctrl or Ctrl-Super - MouseDrag only on the physical upper half. The physical lower half doesn't give drag targets.

Portrait mode should use the same max / mins as a regular monitor, just swap the column and row values.
Personally, I will want 2 rows and 1 column on my portrait secondary monitor.

**Comment by GrylledCheez** [comment]
I'll work on it this weekend.

1. allow 1 column for regular and UW
2. check to see if the height is taller than the width and swap as necessary
3. During testing, make sure to have screen 150%

**Comment by GrylledCheez** [comment]
@skewty, can you also give us some debug logs when you try to make it work?

**Comment by skewty** [comment]
Here is a log.  I tried to get a window to go to the bottom half of my portrait monitor but it didn't work. I placed it on the top after giving up.

[wintile.log](https://github.com/Fmstrat/wintile/files/12205359/wintile.log)

**Comment by skewty** [comment]
NOTE: I wont be around / able to do any more testing for around 7 days.

**Comment by GrylledCheez** [comment]
added in [0ee1d4c](https://github.com/Fmstrat/wintile/commit/0ee1d4c9310e5adfea2a1853d613453fc0163a79)

**Comment by skewty** [comment]
I can now use the bottom half of my portrait monitor.
Thanks!

**Comment by GrylledCheez** [comment]
Does everything else work too?

**Comment by skewty** [comment]
Actually, no.
I have been noticing both Gnome Terminal and Gnome Files don't seem to size themselves correctly on my Primary ultrawide in landscape in the top right corner (perhaps other places too). The coloured zone area looks correct in size but when the window sizes itself to the zone it is often smaller or larger than the zone.

Here is a screenshot of both of them in their wrong size snapped into the same zone.


![Screenshot from 2023-07-28 18-01-40](https://github.com/Fmstrat/wintile/assets/9087223/06dd90e6-5cbe-4717-bb41-821abe50c732)

**Comment by skewty** [comment]
My primary is configured as 3x2.
Look what just happened during testing.
Another example of failed sizing.
![Screenshot from 2023-07-28 18-05-27](https://github.com/Fmstrat/wintile/assets/9087223/f0998757-b87d-49f6-afa2-e49bb6670d8c)

In this example you can see that the height of terminal in the middle is wrong. (It should be the same as Files).

**Comment by GrylledCheez** [comment]
Weird. Give us the logs for that and I'll for to it later. Is it just for gnome apps?

**Comment by skewty** [comment]
Don't know if it is only Gnome Apps but I chose them since they would be easy for developers to test with as well.

**Comment by skewty** [comment]
The problem goes away in legacy X11 mode on my system. It only seems to occur in modern Wayland session.
I was able to get non Gnome app to size properly in the upper right corner in Wayland but Files seems to not size correctly most reliably so is great for testing.

**Comment by skewty** [comment]
G-Tile seems to be able to size windows reliably. Perhaps they are doing something extra or different than WinTile? Might be worth a look.

**Comment by GrylledCheez** [comment]
I'll open that as a new issue.
