### ISSUE TITLE
Q: Is there a way to move left/right onto another screen?

### ISSUE THREAD

**Issue by laszukdawid** [Fmstrat/wintile#163]
Hi, question as in the title. I'm looking for something that'd move onto another screen when moving left a window that's already left adjusted. If this isn't possible, then would you be willing to share where in code one might take a chance to update to (try to) achieve this? I'd be happy to contribute if it isn't there already.

**Comment by GrylledCheez** [comment]
GNOME already has key combos to move windows between screens (`<Super>+<Shift>+<Arrow>`) and workspaces (`<Super>+<Shift>+<PageUp/PageDown>`) . Let me know if that works for you or if it doesn't work as you well as you hope.

If it doesn't, write up exactly how you think it should work.

**Comment by laszukdawid** [comment]
Thanks for the quick response. Any chance you could share the version of gnome or how to enable this shortcut?
I'm on up-to-date Ubuntu 22.04 with Gnome 42.9 (X11) and these combinations don't work for me. I remember this being possible in 18.04 (??) which is why I'm looking for it but since... 20.04... I'm out of luck (and patience).

**Comment by GrylledCheez** [comment]
I'm using gnome 42.5

https://wiki.gnome.org/Design/OS/KeyboardShortcuts
