### ISSUE TITLE
Support for G45 version

### ISSUE THREAD

**Issue by gilvbp** [Fmstrat/wintile#165]
Hi, could you update to G45 version?
This tutorial might help:
https://gitlab.gnome.org/ewlsh/gjs-guide/-/blob/d4cb8a9fbdf669c791dc24bc1b052e404779157b/docs/extensions/upgrading/gnome-shell-45.md
Thanks.

**Comment by GrylledCheez** [comment]
That one will take a bit of work, but I'm not against doing it. I don't want bother if @fmstrat doesn't check back within the next 2 weeks or so, and I'll just assume he's abandoned the project.

**Comment by gilvbp** [comment]
If you need help, I could help with some code.  Here's the official link. https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm
Best regards.

**Comment by GrylledCheez** [comment]
If you'd like to make a pull-request, aim it at the develop branch and I'll thumb through it.

**Comment by gilvbp** [comment]
@GrylledCheez Hi,  Could you create a gnome45 branch? I'll PR there. Thanks.

**Comment by GrylledCheez** [comment]
The gnome-45 branch has been created. Make sure to follow the style guide in CONTRIBUTING.md

Bear in mind that at a minimum, you'll need to update:
extension.js
keybindings.js
metadata.json

**Comment by GrylledCheez** [comment]
@gilvbp, while you're updating it, instead of using `keybindings.js`, change it to `Main.wm.addKeybinding()`

**Comment by Mouwrice** [comment]
Hi, I just updated to Gnome 45 but I see that migrating this extension to the module system appears to have halted. Are there any plans to continue development or should I look for other similar extension?

**Comment by GrylledCheez** [comment]
Does the Gnome-45 branch work for you? (other than the preferences window)

**Comment by Fmstrat** [comment]
My move is almost complete as well, so I'm back to checking on on projects every now and again.

**Comment by Mouwrice** [comment]
Hi @GrylledCheez 

The version from this PR works for me: https://github.com/Fmstrat/wintile/pull/166
Would be nice if this gets merged!

**Comment by GrylledCheez** [comment]
@Mouwrice, does the prefs window work in that PR?

We can't exactly do a merge because that will make the extension stop working for any non-45 users. So we'll need to do something in the build process.

**Comment by skewty** [comment]
Perhaps maintain two branches or set `"shell-version": ["45"]` in `metadata.json` and move on.

**Comment by GrylledCheez** [comment]
@skewty, there's more to it than just changing the version in metadata.js

The entire import system changed so they're incompatible. My current thought is:
1. write the lines for both sets
2. Add a comment to the end of non-45 lines
3. Comment the beginning of 45 lines with something specific 
4. build.sh will remove some lines and uncomment the others

**Comment by lamarios** [comment]
The import system is not compatible but  if you just set  the shell-version to 45 in the metadata,json older versions of gnome won't be able to install it unless they force it (there's a dconf settings for that i believe).  

That's why i agree with @skewty. Keeping  a legacy < 45 branch for bug fixes on legacy and keep the main branch on 45 only makes sense.

**Comment by GrylledCheez** [comment]
@gilvbp, I updated the develop branch to use Adw for prefs. Can you see if that will run on your 45 branch (make sure you swap the import lines).

**Comment by Mouwrice** [comment]
> @Mouwrice, does the prefs window work in that PR?
> 
> We can't exactly do a merge because that will make the extension stop working for any non-45 users. So we'll need to do something in the build process.

@GrylledCheez ow, sorry for the late reply. The prefs window did indeed not work. I do not know if it does with your new changes. 

But I have moved on from Gnome to [Hyprland](https://hyprland.org/), as I have been plagued by tremendous performance issues. (https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6221) So I lost any interest and confidence in Gnome :disappointed:

**Comment by TimeLincoln** [comment]
Very interested to see gnome 45 support for this extension.  gnome 45 branch working for me for now (minus preferences window), also not maximizing when touching the center of the top panel, but works on my second monitor when i hit top center of the screen with no panel.

**Comment by GrylledCheez** [comment]
fixed in #179
