### ISSUE TITLE
hotkey issues between screens

### ISSUE THREAD

**Issue by burakaksoy** [Fmstrat/wintile#167]
If there are two displays side by side and the main display is set as the right display, the win+arrow key shortcut does not move the windows between the displays.

**Comment by GrylledCheez** [comment]
My main display is on the right, and it works as expected. Tell me what you're doing and how you expect it to work. Also, upload a log file around the time it fails.

**Comment by GrylledCheez** [comment]
@burakaksoy, don't forget to tell us your gnome version and extension version

**Comment by GrylledCheez** [comment]
@burakaksoy, try `<SUPER>+<CTRL>+<SHIFT>+<Left or Right>`. Is that what you're looking for?

**Comment by GrylledCheez** [comment]
@burakaksoy, I think @Fmstrat was able to reproduce your problem.  Sorry for the misunderstanding.

**Comment by burakaksoy** [comment]
Sorry for the late reply; I realized it only fails because of the dock position on the screen. I was using the dock on the left side of the screen; it behaves like a wall for the hotkey. When I remove the dock to, for example, the bottom of the screen, it works as desired.

**Comment by GrylledCheez** [comment]
the dock issue will be fixed with #171
