### ISSUE TITLE
preview area with dock doesn't work properly

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [Fmstrat/wintile#168]
Title I recommend for this issue: 

> Usability Problems in WinTile - drag area is too small, and works only to the right of the launcher bar in the left-hand pane of the screen

I'm temporarily switching back to [WinTile Reloaded](https://github.com/ElectricRCAircraftGuy/wintile-reloaded) until someone can fix this, because it has better usability for my needs. I really appreciate your work in WinTile though, and hope to see these bugs fixed in WinTile so WinTile Reloaded can die as a fork.

I'll update my answer [here](https://askubuntu.com/a/1446690/327339) accordingly.

## 2 bugs I'm hoping to see fixed in WinTile: 

1. WinTile no longer snaps windows if you drag to the far left-hand side. You have to very carefully drag it just to the right of the launcher bar instead of all the way to the left of the screen. WinTile Reloaded works fine dragging all the way to the left of the screen. I think this is a recent regression in WinTile. See screenshots below. 
2. WinTile has a too-narrow band you must drag it to for 1/2-screen snap instead of 1/4-screen corner snap. WinTile Reloaded is more usable in this regard too. See screenshots below. I think this is a long-standing problem in WinTile, not a recent regression.

### My WinTile settings: 

![image](https://github.com/Fmstrat/wintile/assets/6842199/29cd2968-abd6-4605-a416-5c5b184beae0)

My WinTile Reloaded settings:

![image](https://github.com/Fmstrat/wintile/assets/6842199/7662d2ae-99d7-4ed6-979d-f6e59abedce3)

### Note

_It would also be nice if you'd put the commit hash of the version being run into the name or settings when you build it, so we can easily see exactly which version and commit hash we are running. Here's my answer on how to easily get the commit hash in Bash. [See `git_get_short_hash`](https://stackoverflow.com/a/76856090/4561887). See the bottom of that answer for how to do it in Python too._

### Screenshots showing the snapping behaviors:

This yellow box is the area I must drag a window in **WinTile** for it to snap to the left 1/2 of the screen. Notice how narrow (left and right) and short (top to bottom) it is, and how I must be to the *right* of the launcher bar for it to even work:

![Selection_173_wintile](https://github.com/Fmstrat/wintile/assets/6842199/cb3d1c71-089a-4782-80df-5354809a514a)

Contrast this to **WinTile Reloaded**, where I can drag it all the way against the left-side of my monitor, and in which it has a much larger area I can drag it to to get the desired behavior, as indicated by this yellow box. WinTile Reloaded is therefore far easier and faster to resize and snap a window to where I want: either a corner or a side.

![Selection_173_wintile_reloaded](https://github.com/Fmstrat/wintile/assets/6842199/36ca2b10-945f-4520-9e97-00992c489573)

**Comment by ElectricRCAircraftGuy** [comment]
I don't know why WinTile is having this problems at all. WinTile Reloaded had fixed all this. I think WinTile should have been rebased onto WinTile Reloaded and then continued to develop from there. Apparently this didn't happen.

**Comment by GrylledCheez** [comment]
Enjoy Wintile Reloaded!

**Comment by ElectricRCAircraftGuy** [comment]
@GrylledCheez , 

Ah, that's too bad. I really appreciate your work on WinTile and was really hoping you'd fix it in WinTile. This makes me sad. :(

WinTile Reloaded is more-usable at the moment, but is a dead project. WinTile is where it's at, and I hate keeping the fork alive just so it can work.

**Comment by ElectricRCAircraftGuy** [comment]
Apparently I came across wrong. I'm sorry.

**Comment by GrylledCheez** [comment]
I suggest you increase the preview distance. The halfwidth snap changed to allow for more rows. 


But with the incoming Gnome 45 migration, I not sure if I'm going to continue on with this beyond the #166 pull request. But it's not my project.

**Comment by ElectricRCAircraftGuy** [comment]
Setting the `Pixels from edge to start preview` from 25 to 150 doesn't fix it. The area is still only to the right of the launcher bar--not extending to the left of the screen, and still very short top to bottom, rather than taking 1/2 the vertical space like it should.

**Comment by ElectricRCAircraftGuy** [comment]
> But with the incoming Gnome 45 migration, I not sure if I'm going to continue on with this beyond the #166 pull request. But it's not my project.

Sounds like WinTile development is dying too then?

**Comment by GrylledCheez** [comment]
If you want the center snap area to be larger change the 5 in row 799 to be 2.

Call it a favor.

**Comment by ElectricRCAircraftGuy** [comment]
Note to self: https://github.com/Fmstrat/wintile/blob/d33631a0ac4e6260332e8d8fe2923492b779feb3/extension.js#L794-L800

**Comment by GrylledCheez** [comment]
@ElectricRCAircraftGuy, I'm going to clean up this comment section. I was having a rough day.  But I can reproduce your issue now.

**Comment by GrylledCheez** [comment]
@ElectricRCAircraftGuy see if #171 works for you
