### ISSUE TITLE
Maximize window when drag to Top center not working in Gnome

### ISSUE THREAD

**Issue by Anduril97** [Fmstrat/wintile#173]
Hey! Love your extension. I am finding when I drag to the top center the window does not maximize. The keyboard shortcuts all work great, just the mouse dragging to top center does not seem to work consistently for me.

Upon further testing it may just be that I need to bring the cursor basically Exactly to the top center, any way the range can be widened a bit so maybe the whole top of the screen is a hot zone for maximize, and leaving up to 10-15% on each side for the corners to activate or so?

Running Wayland Manjaro Gnome 44.4

**Comment by GrylledCheez** [comment]
Look at the develop branch. We widened it back up a bit.

**Comment by GrylledCheez** [comment]
Fixed in b9009d5
