### ISSUE TITLE
Vertical monitor using full width instead of half

### ISSUE THREAD

**Issue by DevGrohl** [Fmstrat/wintile#174]
I would like to have the option to imitate the behavior on W11 for Portrait mode where the edge at 1/4 or 3/4 of the length makes the window take full width instead of half creating a ridiculous small window.

If it's not possible for you to implement it could you point me out to the sections of the code where it detects the hot edge and window resizing?

**Comment by GrylledCheez** [comment]
1st of all, awesome name. 
2nd,take a screenshot of what it currently does, and another of what you want it to do.

**Comment by GrylledCheez** [comment]
If you could also make a red circle where you're putting the cursor.

**Comment by DevGrohl** [comment]
Thank you,

Sorry I'm not used to work within Github for... reasons, so this was the best explanation of how it currently behaves that I could come with: 

[Example](https://youtube.com/shorts/3wgJdu_KvFY?feature=share)

I think it could be an option to use the space marked as blue for a hot corner to resize to full width and keep the rest as it is: [Picture](https://imgur.com/a/Okgdajp)

**Comment by GrylledCheez** [comment]
If you're willing to use the keyboard with the mouse, try
`<SUPER>+<CTRL>+<mouse_drag>`

**Comment by DevGrohl** [comment]
> `<SUPER>+<CTRL>+<mouse_drag>`

It behaves weirdly for me, I see that I can pull the half screen window but seems like the hot border gets bugged. Should I enable debugging information?

I'm also completely open to have a video call if that makes it easier to show

**Comment by GrylledCheez** [comment]
The key combo isn't for a border. It's to let you draw a box of grid squares for your window.

1. Drag your window to the grid you want to start the box (don't let go of the cursor) 
2. Press and hold `<SUPER>+<CTRL>`
3. Drag your cursor to where you want the box to stop
4. Release the cursor
5. Release the buttons

**Comment by GrylledCheez** [comment]
Glad I could help. Don't forget to try the `<SUPER>+<CTRL>+<ARROW>` to grow a window in that direction.
