### ISSUE TITLE
Window sizing via mouse improvements

### ISSUE THREAD

**Issue by Gulluth** [Fmstrat/wintile#175]
When dragging a window using my mouse that I want to take half of my screen real estate, the target area I must move the mouse cursor into is very small. This is true when I want a window on the left or right half. Likewise the target area for maximizing the window is also very small.

I am running Ubuntu 23.04 with a 4k display at 3840x2160 (16:9) resolution and 100% scaling.

**Comment by GrylledCheez** [comment]
Use the develop branch. The area was re-enlarged.

**Comment by Gulluth** [comment]
Thank you @GrylledCheez, this fixes the issue I reported.
