### ISSUE TITLE
Minimum screen edge distance for mouse preview/snap

### ISSUE THREAD

**Issue by justin-shepherd** [Fmstrat/wintile#18]
The minimum distance between the screen edge to the window in showing the mouse preview is too much. Somewhat hard to describe so I've attached an image of what I'm explaining:

![2020-02-06_20-16](https://user-images.githubusercontent.com/4710051/73924033-edc2c580-491f-11ea-924b-a7f4a20489c4.jpeg)

The red areas are the minimum screen edge distance before a preview shows.

Understandably, I can see how this may be considered a look and feel issue, however, personally this has interrupted my workflow a considerable amount to the point I felt it necessary to raise an issue. For comparison, In Windows, The mouse preview shows when you drag to the absolute edge of the screen.

Currently, I'm using 2 column mode, however, this is apparent in all column settings. 
Is it viable enough to have a setting where the user is able to set the minimum padding/edge radius? Assuming 0 would be purely just the edge of the screen before it shows?

**Comment by Fmstrat** [comment]
Sure thing. While I'm in there I will also put in a setting for the preview delay time.

**Comment by Fmstrat** [comment]
Fixed in https://github.com/Fmstrat/wintile/commit/4df818347bdf443a640844f495b15f1bafe9dd51

**Comment by Fmstrat** [comment]
Feel free to rate on extensions.gnome.com once v5 is up ;)

**Comment by Fmstrat** [comment]
Pushed to the extension store and awaiting review. It should show up today.
