### ISSUE TITLE
Version 45-47 support, co-exist with Ubuntu Tile Extension

### ISSUE THREAD

**Issue by GrylledCheez** [Fmstrat/wintile#182]
@Fmstrat, please upload the latest release to EGO.  It is specifically for gnome-45

**Comment by GrylledCheez** [comment]
@Fmstrat, wake up.

**Comment by GrylledCheez** [comment]
@Fmstrat, please release the latest 2 releases.

**Comment by GrylledCheez** [comment]
@Fmstrat, come on Ben. Please?

**Comment by GrylledCheez** [comment]
@Fmstrat, it's been 3 weeks

**Comment by GrylledCheez** [comment]
@Fmstrat, I'd like this to be done before April so the people upgrading to Ubuntu 24.04 will get the update immediately.

**Comment by Kerwood** [comment]
Would be nice :)

**Comment by GrylledCheez** [comment]
@Fmstrat, it's been a month.

**Comment by danieldemus** [comment]
@GrylledCheez Maybe you need to fork wintile with a new name and create a new plugin on EGO?

**Comment by GrylledCheez** [comment]
@danieldemus, yeah. I talked to EGO and they said the same thing. Give me a good name that isn't too weird and I'll try to submit it this week. (Wintile-Reloaded is taken)

**Comment by danieldemus** [comment]
Well, there are the classics "new"," continuity", "next", "ng" or "nl" (new leadership). wintile 1.1?
It's never really satisfactory.

**Comment by GrylledCheez** [comment]
@danieldemus, I'm going to go with "Wintile-Beyond". I like Batman.

**Comment by GrylledCheez** [comment]
@Fmstrat, did you wait for me to start making my fork separate to come back and make changes to the main repo? Or is that just a coincidence?

**Comment by mrchantey** [comment]
I'm on gnome 46, any chance of getting a version for that too? This extension looks exactly what im looking for :)

**Comment by GrylledCheez** [comment]
I've decided to split off from the main repo as "Wintile-Beyond". This works on both 45 and 46. 
*BE SURE TO DISABLE ANY OTHER TILING PROGRAMS, INCLUDING WINTILE*

https://github.com/GrylledCheez/wintile-beyond/tree/develop

**Comment by mrchantey** [comment]
Awesome thanks, had no problems building from source per instructions.

**Comment by GrylledCheez** [comment]
@mrchantey, thanks for reminding me to rewrite the build instructions for the README.MD

**Comment by GrylledCheez** [comment]
I have officially published Wintile-Beyond at https://extensions.gnome.org/extension/6970/wintile-beyond/

Tell your friends.

**Comment by Fmstrat** [comment]
Updated for proper GNOME 43-47 with a single code-base support. Previous updates killed future releases for v43, which is still in use by Debian LTS. Release incoming with submission to Gnome Extensions.
