### ISSUE TITLE
import declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by bennuttall** [Fmstrat/wintile#183]
First of all, just want to say thanks - I just reinstalled my OS and completely forgot that this was not standard issue. I've been using it for a couple of years now and I had little recollection of how I installed or configured it before, but managed to find this project again.

I did had flashbacks of struggling to install this last time - the bug where the GNOME version number was "40.0" and needed to be changed to  "40"...

Anyway, I digress...

After failing to install it from the extensions browser, I followed the guide in the readme here, and it failed due to the JS error `import declarations may only appear at top level of a module`.

I ended up trying to install the previous GitHub release - which failed in a different way - it didn't find `.local/share/gnome-shell/extensions/wintile@nowsci.com/settings.ui` so I copied `settings.ui` from the repo into that location and it worked.

OS: Ubuntu 22.04 - stock gnome etc

**Comment by GrylledCheez** [comment]
ubuntu 22.04 uses gnome 42. Don't use the Gnome 45 version. Look at the releases page for the previous version.
