### ISSUE TITLE
Sometimes stops working (hotkeys)

### ISSUE THREAD

**Issue by Marwe** [Fmstrat/wintile#184]
Sometimes the keyboard shortcuts to move/resize Windows stop working. I found no clear pattern yet, this might be related to hibernate states and/or switching screen setup.

If I switch the extension off, I get at least the standard gnome functionality back working.
Restarting gnome.-shell often helps to restore the full functionality.
Is there a possibility to reinit the plugin only without reinit of the gnome-shell?

May be unrelated, though I have no idea what changed the settings (may I accidentially while looking at it)
I found the settings were weird with one column only, explaining the following behaviour: super-left and -right keys maximize the window (super-top and -down work).

**Comment by GrylledCheez** [comment]
is this from the Git or from Extensions?

**Comment by GrylledCheez** [comment]
> super-left and -right keys maximize the window in single column mode. 

That's intended behavior for all column counts and row counts. It only looks weird because you're using single column mode.

**Comment by Marwe** [comment]
Hm, it seems to be related to display changes, plugging USB3/thunderbolt off or on can trigger it (happened multiple times today - without logging). However, I found this alias in my config to quickly reload wintile from cli :)

```
alias wintile='gnome-extensions disable wintile@nowsci.com;gnome-extensions enable wintile@nowsci.com'
```

**Comment by GrylledCheez** [comment]
Wintile doesn't have logging of its own. It sends logs to journald that start with "[Wintile]" , and we are merely grepping for that string in the command on the README.MD

Wintile can't emit anything about the USB.

**Comment by gazhay** [comment]
I have had intermittent problems over a few years with the hotkeys stopping working.

I used to have a script which ran when I woke the screen to disable and reenable wintile and that fixed it. 
You could also bind a script to a key for the same purpose

**Comment by Marwe** [comment]
@gazhay where is and what would be a proper hook? "screen wakeup"/"recover from suspend" or "display setup changed" come to my mind, I did not find one yet, therefore defined the alias.

I lately found in that situation gnome-shell throwing lots of messages into logging with `scrollView.vscroll is null` and more, the logging alone needed a hell of resources.
I have another alias to restart the gnome-shell (works from a terminal session, too):
`alias gnomeshellrestart='echo "gnome-shell --replace -d" $(w| grep "$USER"| awk "{print \$3}"|grep ":"|head -1)| at now'`

**Comment by Fmstrat** [comment]
@iaakki Ubuntu has added in it's own Tiling extension, which could be conflicting. I've just added code to support this in v18/v19. Once everything is released and you've updated, please let me know if you're still having issues.
