### ISSUE TITLE
[Feature request] customize drag zones

### ISSUE THREAD

**Issue by TMDouglas-CompSci** [Fmstrat/wintile#185]
I installed this extension, and it works very well except for one thing: the size of the zones for making a corner-window. Put simply it is very hard to make a half-screen window, as roughly 80% of the edge is dedicated to making windows in the corner. I feel that the extension would be improved if there was an option in the WinTile config to allow users to customize the size of the zones for snapping the windows. 

For example: I have my monitor configured to a 2-column 2-row setup. On my 34" ultrawide the entire vertical dimension is approximately 13 1/8", and the total length that can be used to make a half-screen window is approximately 2 1/4". This means that roughly 17% of the edge of my monitor can be used to make a half-screen window. The issue with this is that when quickly dragging windows around that is not an easy zone to quickly hit, leading to me constantly having to resize windows to get my windows correct. It would be much better if I could resize the snapping area for corners to be the actual corners, and not the majority of my monitor's edge.

**Comment by GrylledCheez** [comment]
I might look into that. But why not use `<SUPER>`+`<LEFT/RIGHT>`?

**Comment by TMDouglas-CompSci** [comment]
That works, but I would imagine many users still prefer dragging windows around when arranging multiple windows. It's not a major issue, and I would be able to adjust over time, but I figured that submitting a feature request would still be helpful for future users were this implemented.

**Comment by GrylledCheez** [comment]
I think I'll make an option to show the hotzones. That might alleviate confusion a little bit. Want to do a pull request?

**Comment by GrylledCheez** [comment]
Please move this issue to https://github.com/GrylledCheez/wintile-beyond/issues

I'll do my best to get it implemented This month.

**Comment by t-c-acc** [comment]
I wanted to request the same feature. I, and I assume many users, usually want a half-screen tile and some times a quarter tile. It would be nice to have an option with which I can make most of the screen edge to half-tile on drag and only the corners to quarter-tile.

I don't know if Wintile-Beyond implements something like this now, since I use Debian (GNOME 43.9), but it would be nice to have this functionality in this extension.
