### ISSUE TITLE
Terminal Windows do not have the Proper Size

### ISSUE THREAD

**Issue by Hosein-Rahnama** [Fmstrat/wintile#186]
I am using winTile on Ubuntu 20.04 LTS. All things work properly except for the terminal windows. There is always a gap between terminal windows and other windows. See the following examples.

![Screenshot from 2024-03-20 14-53-06](https://github.com/Fmstrat/wintile/assets/88373622/f37b4c9e-b566-49ab-87f3-ed423a13a17c)
![Screenshot from 2024-03-20 14-50-07](https://github.com/Fmstrat/wintile/assets/88373622/9555abf7-1429-4482-a8c5-efb840424815)

**Comment by pramodhrachuri** [comment]
I have this problem too.
I am using Ubuntu 22.04.4 with Gnome 42.9.

![image](https://github.com/Fmstrat/wintile/assets/13718503/1692fc51-c5f9-486d-a01e-5b525e374a21)

**Comment by Fmstrat** [comment]
This has to do with the font size in your teminal window. Unfortunately we can't correct this since the default Ubuntu terminal scales this way. Sorry :(
