### ISSUE TITLE
Gnome 46

### ISSUE THREAD

**Issue by lommes** [Fmstrat/wintile#187]
Hi,

this extension does not work with Gnome 46

`TypeError: Main.uiGroup.add_actor is not a function.`

I was able to fix this by replacing 
`Main.uiGroup.add_actor(preview);`
with
`Main.uiGroup.add_child(preview);`
in https://github.com/Fmstrat/wintile/blob/c2d6e2e5b71760244b4814baa6250826e2377f3c/extension.js#L1158

I think this change might break the extension for older versions, and I'm not sure how to test/fix it.

https://gjs.guide/extensions/upgrading/gnome-shell-46.html#gjs

**Comment by atassis** [comment]
I have applied this fix, it works, but have another issue with windows. When you click `Super + Right` while the window is maximized- it will statter to the right side and then move back to maximized. But if u continue holding the combo- it will statter for half a second, but finally get to the right side of the screen.

**Comment by GrylledCheez** [comment]
@lommes and @atassis, can you please check out this commit?  If it works for you 2 I'll make some more style/documentation edits then submit it to the extension repo to continue with the development myself.

https://github.com/GrylledCheez/wintile-beyond/tree/gnome-46

**Comment by atassis** [comment]
Hi there. Is your request still actual?

**Comment by GrylledCheez** [comment]
yes. Build that and test it out. It works on my 46. Maybe any future issues on my fork.
