### ISSUE TITLE
Feature Request: Support dragging windows on touch screens

### ISSUE THREAD

**Issue by shade-belisar** [Fmstrat/wintile#189]
Currently, dragging windows via touch screen does not trigger tiling, when the same motion while dragging with a mouse does. This is a regression from default behavior, where dragging and tiling / full screen is possible via touch (but unfortunately only half screen, not quarter).

I would love to see dragging and tiling enabled via touch screen, the same way it is enabled via mouse.

**Comment by GrylledCheez** [comment]
can you tell me where it worked in the past? also, make this request on
GrylledCheez/wintile-beyond

**Comment by shade-belisar** [comment]
Not in the past, but in Vanilla GNOME without the extension. But unfortunately only for full and half screen, not quarter.
I've opened an issue at the other repository.
https://github.com/GrylledCheez/wintile-beyond/issues/14
