### ISSUE TITLE
Nice idea and clean implementation

### ISSUE THREAD

**Issue by scherepanov** [Fmstrat/wintile#19]
It is a very nice idea how to control tiling with only `<Super><Arrows>`, for several columns, and 2 rows.
Have you thought how to control several columns by several rows in a same way?
And, your code is very clean.
I think I can rather transparently add similar functionality to gTile.

**Comment by Fmstrat** [comment]
@scherepanov Thanks for the feedback. Yes, I think that would be a possibility by building out a grid. The multi-column support was added in rather quickly so I did it the manual way instead of calculating a grid.
