### ISSUE TITLE
Not supported on Ubuntu 24.04

### ISSUE THREAD

**Issue by uzy-92** [Fmstrat/wintile#193]
Currently unable to install this extension as this is unsupported on the new version of GNOME (46) 

Is there a  plan to release a new version ?

**Comment by avallbona** [comment]
@uzy-92 there is a fork extension https://extensions.gnome.org/extension/6970/wintile-beyond/

**Comment by uzy-92** [comment]
I have installed this but it doesn't seem to be as good as wintile? 

I could have quarter windows using CTRL + arrow keys but this does not work no more, and the fork extension doesn't have any settings so I can amend

**Comment by GrylledCheez** [comment]
It's ctrl+super+arrow.
