### ISSUE TITLE
Make this extension work with drag resize?

### ISSUE THREAD

**Issue by ermo** [Fmstrat/wintile#2]
Would it be possible for this extension to place nice with the existing mouse-grab-and-resize functionality of GNOME Shell?

There's an obvious way to group windows in this scenario, but it's difficult to describe in text. I would suggest simply doing it like i3 does it when the screen is divided into 4 equal quadrants.

**Comment by Fmstrat** [comment]
This is a potential, yes. Right now there is no code in place to track the mouse and I'm not sure if I can override GNOME's default. Other apps using holding a key to track, but I'm not a big fan of that from a usability standpoint. I will investigate this.

**Comment by Fmstrat** [comment]
We now have mouse grabbing built in to handle restore on move. That's the first step to tracking mouse movement. I'll take a look at how https://github.com/tobias47n9e/ScreenCoordinates is function next to see if I can get this in for the release after-next.

**Comment by Fmstrat** [comment]
@ermo The first beta is in `develop` if you would like to try it out. I'm still working on overriding GNOME's default maximization, but dragging to individual quadrants works pretty well.
