### ISSUE TITLE
Support operation with GTK Title Bar

### ISSUE THREAD

**Issue by Tumerskiy** [Fmstrat/wintile#23]
Hi,
Nice job with this extension!

Some configurable via settings things can potentially raise the experience even further: 

1) Jump to the screen/workspace to the left/right/up/down. Like in windows10 when the window is snapped to the side of the screen to which there is another screen attached, window can jump to the next screen on the secondary hot key press. If there is no next screen that direction, but possible dynamic/static workspace - move there with respect to allowed dimension for the workspaces (vertical/horizontal). 

3) There are extensions like "GTK titlebar" which allow top panel be merged with window title bar, looks like native snapper supports it, so when the window is snapped to left or right, title bar remains merged with panel. It will be nice to have if this is also supported.

BR
Tumer

**Comment by ba32107** [comment]
Hi,

Although I am not the maintainer, allow me to reply:

1. This is already supported for jumping to other screens. I did notice a bug with this behavior that I believe might be causing you this problem. I have raised #25 to track it, please have a look and see if it solves your issue.

Jumping to other workspaces is not supported I believe, and I think it would be a nice feature. I recommend creating a separate issue for that and keep issues focused on a single bug or request.

2. I don't understand what you mean here, would you mind explaining further? Please provide screenshots if you can.

**Comment by Tumerskiy** [comment]
Hi,

1. I can confirm that window jumps as long as the screens are aligned by the top side. I believe it's a bug.
The jump to workspace in my description is tightly coupled with the jump to screen. I imply the same hot key invocation with the decision to jump based on what is available at particular direction with preference to screen.
2. Using "GTK title bar" extension.
Maximized window with native snapper:
![image](https://user-images.githubusercontent.com/36116979/80712227-a9c70300-8abf-11ea-8108-4e5e15de1b34.png)
Snapped to the right with native snapper:
![image](https://user-images.githubusercontent.com/36116979/80712312-ce22df80-8abf-11ea-9aeb-a0f29fbfd56f.png)
Snapped to right/top right quarter with WinTile:
![image](https://user-images.githubusercontent.com/36116979/80712468-06c2b900-8ac0-11ea-8e98-72b0905e17f2.png)



BR
Tumer

**Comment by ba32107** [comment]
> The jump to workspace in my description is tightly coupled with the jump to screen. 
Understood that the behavior is coupled from a user's perspective, but the implementation might be completely different. I recommend opening a separate issue for that, and use this to track GTK title bar support.

**Comment by skewty** [comment]
All current versions of JetBrains IDEs support "New UI" which have menu integrated with windows controls.

The 2. feature can never be more than half-baked and should be closed in my opinion or leave it purely for 1?

We use WinTile to tile (at least 2) windows. If both the left and right tiled windows want 
> like "GTK titlebar" which allow top panel be merged with window title bar

then it can't be done.  The GTK titlebar doesn't support absolute positioning for window control buttons as far as I understand it.
What if I set columns to 5 and tile 5 windows?  Then I have 5 sets of window controls?  
Now what about 5 columns and 2 rows? What about the window controls for the 2nd row?

**Comment by GrylledCheez** [comment]
I'm good with closing it
