### ISSUE TITLE
Snapping to other screen does not work if the Y coordinates are too far apart

### ISSUE THREAD

**Issue by ba32107** [Fmstrat/wintile#25]
I have a 27'' external display that I use with my laptop, the screen of which is much smaller. I had them set up like so. Note that the smaller screen is vertically in the middle of the larger one:
![image](https://user-images.githubusercontent.com/26036493/80678634-37502600-8ab3-11ea-9af5-137810b2ce40.png)

This breaks the ability of snapping windows across screens. I believe the root cause is this:
https://github.com/Fmstrat/wintile/blob/master/extension.js#L218

If I arrange the screens to be aligned vertically, then it works as expected:
![image](https://user-images.githubusercontent.com/26036493/80678745-72eaf000-8ab3-11ea-85b4-1e89be6ecc6b.png)

I spent a lot of time debugging this, because the root cause was not straightforward at all, so I believe this might affect other people. I will have a look at this and propose a solution when I have some time, but it'd be great to hear your thoughts.

**Comment by Tumerskiy** [comment]
I can confirm the behaviour. The hop to next screen is only available with top alignment of the screens.

**Comment by Fmstrat** [comment]
This is a feature not a bug ;)

If you are using stacked monitors, say a 3x2 grid, the system needs to know how to switch left/right. I will look into making this value adjustable.

**Comment by ba32107** [comment]
Ah I see! Makes sense. However I believe the user should not have to configure this, or the very least it should be straightforward why the snapping does not happen with not aligned screens.

I think the good solution here would be to allow left-right snapping all the time if the user only has two screens. I would assume the large majority of users are not using stacked screens, so the default setting / behavior should probably cater to the majority.

(I did not check how this bit of the code works yet, might be really easy or very challenging)
