### ISSUE TITLE
Add option to ignore Activities Hot corner

### ISSUE THREAD

**Issue by loligans** [Fmstrat/wintile#28]
When moving a window to the absolute NW corner of the monitor WinTile does not perform a resize.

When moving a window to any other corner (SW, SE, and NE), WinTile performs a resize as expected.

I suspect that the Activities Hot Corner is the culprit, preventing WinTile from resizing. I propose disabling Hot Corner while the window is Grabbed and re-enable when the window Grab has ended.

**Comment by GrylledCheez** [comment]
Please reopen this if it's still an issue.
