### ISSUE TITLE
Making possible to use top or bottom of screen?

### ISSUE THREAD

**Issue by quasipedia** [Fmstrat/wintile#3]
I'm not a Win user, so I don't know if there's some non-obvious reasons why the following is undesirable, but...

...I would have expected the behaviour of the arrows to be consistent on the X and Y axis.  That's to say: if I am on a ¼ window on the top left of the screen and I press :arrow_down: I get for the first press ½ window occupying the full left size of the screen, and for the second a ¼ window at the bottom left.  I would expect, in the same starting scenario, the same behaviour for the :arrow_right: (first click: full top half, second click ¼ on the top right).

Currently (at least on my system, Fedora 30) the :arrow_right: and :arrow_left: keys only move the ¼ windows right and left.

**Comment by Fmstrat** [comment]
The goal of this extension was to help Windows user's transition over, which means if I expand I would mirror the Windows 10 functionality which is exactly what you describe for occupying the left, however a full top/bottom half is not their functionality.

That being said, this could easily be added to the configuration (once I add that in) in the same section where you will be able to configure grid size.

**Comment by Fmstrat** [comment]
Added this feature in `develop`, will be in next release.
