### ISSUE TITLE
bug: strange window behavior on demaximize

### ISSUE THREAD

**Issue by derVedro** [Fmstrat/wintile#35]
If you drag maximized window with mouse it show up somewhere left from your mouse cursor. I made a video: 

https://idiod.video/cxowz2.mp4

what you see there:

0:03 - 0:07 maximize/demaximize with double click on title bar - 👌
0:07 - 0:11 maximize by putting the window to top of the screen / demaximizing by grabbing it from there - 👎
0:18 - 0:30 the same as befor but with turning off wintile extension - 👌

I use 2 monitors and Ubuntu 20.04. I can reproduce it even if all my other extensions are disabled.

**Comment by GrylledCheez** [comment]
Please reopen this issue if it's still a problem.
