### ISSUE TITLE
Strange behavior under Wayland and one key difference to Windows 10 snap

### ISSUE THREAD

**Issue by vincentmathis** [Fmstrat/wintile#37]
When I have a floating window and I press Super + Left or Super + right, the window maximizes vertically but stays at its horizontal position. Pressing Super + left or Super + right afterwards does nothing, pressing super + up or super + down on the other hand will move the window in the corner, depening on the left/right direction of the previous hotkey.

Moving between quadrants seems to work but if the window is vertically maximized, let's say on the left side, pressing Super + right will do nothing.

I suspected this was an issue and switches to Xorg where it worked fine **execpt** one key difference to windows 10 snap: When I press Win + Left in Windows and afterwards press Windows + Right, the window will go back to its original floating position. With wintile on the other hand it will immediately go to the opposite site of the screen. This makes it incredibly hard to move the window back to floating, the only way I found was to maximize the window with 2x Super + Up and then Super + Down again. I would suggest to implement this to resemble the windows behavior.

**Comment by stloewen** [comment]
Same Problem. Manually installed it under Ubuntu 21.10. Works fine in a X11-Session, tiles incorrectly in a Wayland-Session.

**Comment by GrylledCheez** [comment]
Please reopen this issue if it's still a problem
