### ISSUE TITLE
Get this into GNOME by default

### ISSUE THREAD

**Issue by claell** [Fmstrat/wintile#4]
Currently GNOME already claims to support `Super + Up / Down / Left / Right` (while `Up / Down` does not work for me unfortunately).

So the addition of this extension seems to mainly be the 1/4 tiling. This would also be rather useful to have integrated directly into GNOME. I hope this can be done without much problems.

**Comment by Fmstrat** [comment]
While I would certainly be open to contributing to GNOME, I'd need someone to seed the idea with them. If they were interested, I would dive into testing against stacked monitors and configurable grids (ultra-wide monitors may want a 6x4 or 8x4 instead of a 4x4), first.

**Comment by claell** [comment]
I could create an issue for that and wait for their response. Nice to hear that you are open, let's hope they are too.

**Comment by Fmstrat** [comment]
@claell I chatted with the dev team in IRC, and have filed your request in the existing bug entry for quarter monitor docks: https://bugzilla.gnome.org/show_bug.cgi?id=696130

**Comment by claell** [comment]
Nice to hear that! I left a comment on that issue.

**Comment by ba32107** [comment]
Was there any progress made on this? I'd also love to see this in Gnome by default.

**Comment by claell** [comment]
I don't know. Maybe nobody from GNOME responded to the proposal? At least the bug did not get a reaction afterwards. Maybe this is lacking some awareness from the right people.

**Comment by olibre** [comment]
I have just added a comment on a recent issue on the new GNOME bug tracker:
https://gitlab.gnome.org/GNOME/mutter/-/issues/966

**Comment by claell** [comment]
@Fmstrat From what I read on the GitLab issue above, the GNOME devs seem to be open to contributions, if their requirements are met. Not sure whether that is already the case with this project and whether it is easy to transfer that to the upstream code.
