### ISSUE TITLE
Feature Request: Let us choose up to 4 rows

### ISSUE THREAD

**Issue by erihanse** [Fmstrat/wintile#41]
It would be nice if we could also have the option to have more than two rows.

**Comment by GrylledCheez** [comment]
@erihanse,I know it's almost 4 years later, but I'm working on it.

**Comment by GrylledCheez** [comment]
- [ ] add rowCount for grid math
- [ ] add shrinking for up
- [ ] add shrinking for down
- [ ] create preview grids for new rows

**Comment by GrylledCheez** [comment]
@Fmstrat, can you come up with down shrinking that won't interfere with unmaximizing?

**Comment by GrylledCheez** [comment]
#148 is ready for testing and merging. Whoever sees this, please let me know if it works for you.

**Comment by GrylledCheez** [comment]
merged #148 into develop branch
