### ISSUE TITLE
Resolution/screen-dependent amount of columns?

### ISSUE THREAD

**Issue by nekohayo** [Fmstrat/wintile#45]
I have two monitors: one at 2560x1080 and one at 1920x1080. In the first case it makes sense to have three tiling columns sometimes (but sometimes not, depending on the application!) and on the other (1920x1080) monitor it pretty much never makes sense for me to triple-tile.

Ideally I'd like this extension to be able to have per-screen-width columns.

And potentially, alternatively, configurable keyboard shortcuts. For example I would like to continue to use Super+left/right to half-tile on any screen, and use some other keyboard shortcut (Super+1/2/3 ?) to tile in thirds (ex: Super+2 to tile to the center third of the current screen), though it seems as if GNOME Shell is already using those shortcuts for something (switching between windows somehow)...

**Comment by GrylledCheez** [comment]
Ultrawide-only mode added in #109 

This will make any monitor with a ratio of less than 1.9 be forced to 2x2 grid.  We might allow 3x2 mode if there's a want for it.

Let me know if there are any issues with it.
