### ISSUE TITLE
Allow window to expand to multiple columns

### ISSUE THREAD

**Issue by bestrandomnameever** [Fmstrat/wintile#46]
Really loving the granularity of having more than 2 columns, but it would be nice to be able to have windows that span multiple columns. I was thinking that perhaps a couple of additional shortcuts to "grow" windows would be a way to achieve this.

Example (using Alt+Direction keyboard shortcuts as placeholder):
- Starting with a 3 column layout where a window takes up the top of the center column
- Alt-Right => Window grows so it takes up the top "row" and spans over the center and right column 
- Alt-Left => Windows grows so it takes up the entire top row, spanning all columns

**Comment by manfreed** [comment]
As a workaround, you can make a window fill the screen, and then shrink it to your desired size, which kinda makes you achieve what you just proposed, but sure, it would be great if you can grow the window too. 

I don't recommend using Alt+arrows for this, some productivity apps rely on this.
I believe all window management keyboard shortcuts should require the super key.

**Comment by GrylledCheez** [comment]
If we were to implement this, how should we differentiate between the left of a window growing left vs the right side of a window shrinking to the left?
