### ISSUE TITLE
Feature request: gaps

### ISSUE THREAD

**Issue by Itookmyprozac** [Fmstrat/wintile#47]
When you tile the windows the monitor looks like a crowded elevator. Adding gaps between them or at least giving the option to the user to add them would be great!

**Comment by RayDeCampo** [comment]
I'm having the opposite problem - I have gaps and I don't want them (or they are too big).

The lesson, as always, users are never satisfied. ;-)

**Comment by rsxchin** [comment]
@Itookmyprozac, would you want a buffer around the whole tile, or just on the left and right sides?

**Comment by rsxchin** [comment]
@RayDeCampo, what kind of gaps were you having? I've got some commits in progress that will remove the 2 px gap on the right in 3 column mode.

**Comment by RayDeCampo** [comment]
@rsxchin thanks for asking - however I haven't been using wintile lately (trying out KDE) so feel free to disregard my preferences.

**Comment by GrylledCheez** [comment]
@RayDeCampo,GET BACK HERE AND TRY MY GNOME STUFF!!!!!!!!!!!

**Comment by GrylledCheez** [comment]
also, the error you were describing is solved in 45c7b556855370d477b509cf1029b196d6ccd7e1 and merged in #124

**Comment by GrylledCheez** [comment]
@Itookmyprozac would you mind trying out #133 and see if that's what what you were asking for?

**Comment by GrylledCheez** [comment]
merged into develop in #133

**Comment by Itookmyprozac** [comment]
> @Itookmyprozac would you mind trying out #133 and see if that's what what you were asking for?

I can't, I don't use Gnome anymore.

**Comment by GrylledCheez** [comment]
That's alright. Thanks for getting back to me anyway
