### ISSUE TITLE
Window flashes while moving it around

### ISSUE THREAD

**Issue by ba32107** [Fmstrat/wintile#5]
First of all, thank you for this extension - it is the only one I found that actually can snap windows into the corners, and can do this intuitively.

The only problem I have is a visual one. When I move the window around the screen, it keeps "flashing". An example:
1. Start with a fully maximized window
1. Super+right to snap it right
1. Super+down to snap it to the lower-right corner
1. Super+up to snap it right
1. Super+up to snap it to the top-right corner

Either step 3 or 5 will definitely flash the window. I suspect this happens because before each resize, you are unmaximizing the window for an instant, which shows up as a flash. I also figured out that the unmaximize is necessary because `app.move_resize_frame` only works with a window that is not maximized in any direction.

I am not sure what a good solution would be though. I googled around a bit, but not familar enough with Gnome. Perhaps it would be possible to disable animations for the duration of the unmaximize operation?

Ubuntu 19.10
GNOME Shell 3.34.1

**Comment by ba32107** [comment]
Hi @Fmstrat, is this repo under active development? I'd be interested in contributing, but would need some help.

**Comment by Fmstrat** [comment]
Hi, yes, this is maintained still. I am very open to contributions, feel free to fork off master and send a PR!

As for what is highest on the priority list, right now it's implementing a settings screen to set grod size (for ultrawide support) and stacked monitor support.

**Comment by ba32107** [comment]
Great, thanks. My top priority would be this particular issue as it really bothers me, I will try to look into it whenever I have the time.

I'd be grateful if you could help out with a few questions, as I'm new to gnome extension development. Do you have any suggestions regarding local dev workflow? What I did so far is simply edit the extension code, reload it, and test - but it's pretty tedious and I'm also unable to debug. Is there a way I can test without having to reload the extension after every change? Also, where can I find the API reference for gnome? It took me suprisingly long to find some API docs last time I tried, and I'm not even sure I was looking at the right page.

**Comment by ViToni** [comment]
> Also, where can I find the API reference for gnome? It took me suprisingly long to find some API docs last time I tried, and I'm not even sure I was looking at the right page.

https://wiki.gnome.org/Projects/GnomeShell/Extensions/Writing
