### ISSUE TITLE
Not tiling to the correct position

### ISSUE THREAD

**Issue by trisct** [Fmstrat/wintile#51]
The windows cannot tile to corners, either by using `super`+`arrow` or by dragging. I suspect it is due to some ubuntu system upgrades.

My system specs:

ubuntu20.04
gnome version 3.36.8
gnome-shell 3.36.4

**Comment by knotdevel** [comment]
I have the same problem, after upgrading libmutter-6-0 package from 3.36.6 to 3.36.7.
My workaround is to change app.move_resize_frame(**true**,...) to app.move_resize_frame(**false**,...) in extension.js.

My environment:
Ubuntu 20.04

Reference:
https://www.reddit.com/r/gnome/comments/kmoeh8/what_exactly_does_the_user_op_paramter_in/

**Comment by johnlawerance** [comment]
I am also experiencing this issue. Attempted the work around @knotdevel suggested and reloading the extension does not appear to fix for me.

ubuntu 20.04
gnome 3.36.8
gnome-shell 3.36.4
libmutter 3.36.7

**Comment by JSkier21** [comment]
Same thing in Arch, half tiling still works across the board, but quarter tiling doesn't work in many apps (ie. pithos, gedit, and most Gnome apps don't work).

The js workaround didn't do anything for me either. 

- mutter 3.38.3
- gnome-shell 3.38.3

**Comment by GrylledCheez** [comment]
This was fixed in #113 

Please reopen this if it's still an issue.
