### ISSUE TITLE
Clicking and dragging on close/minimize/maximize breaks the snap

### ISSUE THREAD

**Issue by kupokunic** [Fmstrat/wintile#53]
So if you accidentally click on one of the window buttons, normally you could just hold the button down and drag of it to prevent the click from happening. However, while that still works here, it breaks the snapping.

Video of it: https://user-images.githubusercontent.com/69876612/106525921-c0691300-64b2-11eb-95e5-4f7a096ef6d0.mp4

**Comment by GrylledCheez** [comment]
Please reopen this if it's still a problem
