### ISSUE TITLE
Support touchscreen devices

### ISSUE THREAD

**Issue by Esokrates** [Fmstrat/wintile#54]
Convertibles / Laptops with touchscreen are much more common these days and may be even more in the future.
This ticket is a mixture between bug report and feature request:

1. BUG: Snapping does not work with touchscreen under Wayland:
Gnome Wayland works very much better in general with touchscreens, however this extension does not work at all with the touchscreen: it makes tiling impossible when dragging the window with the finger, no matter which edge I drag the window against. When disabling the extension half tiling works again.

2. RFE: Allow for one column only for horizontal mode
I am using an XPS 13 2-in-1 and use it in tablet mode for taking notes with a stylus. Often I want to tile windows the following way: Upper half for note taking, lower half for a document viewer or a browser window. Right now I have to manually resize the windows to get that which is pretty inconvenient. Would be great if you could opt for selecting 1 column by default when the display is rotated.

**Comment by GrylledCheez** [comment]
@Esokrates, just curious if this works with touchscreens right now.

Please reopen this if it's still an issue.
