### ISSUE TITLE
does not work with PopOS 20.10

### ISSUE THREAD

**Issue by D1Ck3n** [Fmstrat/wintile#55]
Good day,

I'm currently trying out PopOs 20.10 with Gnome 3.38 on my workstation and I'm bothered that I can't get the Windows 10 style tiling to work (have always used cinnamon so far). Now I've seen your extension and was first excited! I installed it immediately but unfortunately the default shortcuts (change focus of windows) remain. What can be the reason for this?

Best regards

**Comment by rsxchin** [comment]
Keybinds on enable/disable have been fixed on the develop branch.
