### ISSUE TITLE
Feature requests: top/bottom edge tiling, top bar indicator, shortcuts discoverability/configurability

### ISSUE THREAD

**Issue by venteto** [Fmstrat/wintile#56]
I'm loving this extension for quarter tiling! My only request would be to add the ability to tile to the top or bottom halves of a screen (like with the ShellTile GNOME extension), and to have a top bar indicator (like with the Pop Shell extension).

Also, in the settings it would be nice to at least see what keyboard shortcuts are set (e.g., for people who don't actually use Windows 10 and have no clue what the shortcuts are in that environment that WinTile is emulating—I don't know which keys to use to tile to specific columns on wide monitors for instance), and possibly also be able to override them with custom settings,

**Comment by GrylledCheez** [comment]
1. Maximizing horizontally at half height has been added
2. Shortcuts are documented in the README and only use `<Super>`+`<Arrows>`
3. There aren't any current plans for a bar indicator, but I'm open if you can explain desired function.
