### ISSUE TITLE
Some Windows (e.g. Gnome Terminal) Do Not Fill Entire Area Available To Them

### ISSUE THREAD

**Issue by Enekk** [Fmstrat/wintile#57]
I am running Debian Testing and am using a version of wintile that has had commit 7dac8cb ("Fix for movement bug for gnome-terminal and [gnome-]terminator") merged into it.  When I send a terminal to the corner, it does not fill the entire corner.  Please see screenshot:
![bad_terminal_corner_fill](https://user-images.githubusercontent.com/1928133/108845170-14937e80-75ab-11eb-8a9e-fded853fb421.png)

In the screenshot, the bottom and right sides of the terminal do not extend to the edge of the screen.

**Comment by manfreed** [comment]
This is because Gnome Terminal's window cannot be freely sized. I don't think this is something to be fixed in this extension, rather in GT itself.

**Comment by GrylledCheez** [comment]
I believe this is fixed. Or at least I haven't seen it come up during my development and testing. Please reopen if it's still an issue in v11.1
