### ISSUE TITLE
Unable to snap Gnome Terminal into certain quadrants in Ubuntu 20.10

### ISSUE THREAD

**Issue by charlesritchea** [Fmstrat/wintile#58]
When I try to move Gnome Terminal into certain quadrants in Ubuntu 20.10 it will restore to the arbitrary original placement instead, it's different quadrants depending on if it's mouse placement or keyboard.

**Comment by hmlendea** [comment]
I also have a problem snapping the GNOME Terminal to the lower quadrants of the screen on Arch Linux. For me though it's a bit different. It does snap there, but it's not snapped perfectly (at all), instead it rests above the screen edge, leaving a gap between the screen edge and the bottom of the terminal.

![image](https://user-images.githubusercontent.com/10261133/131324758-85203517-add0-4bfa-bd96-3310c26393c3.png)

**Comment by GrylledCheez** [comment]
Please reopen this if it's still an issue.
