### ISSUE TITLE
<super><shift> LEFT/RIGHT/UP/DOWN to make screen larger

### ISSUE THREAD

**Issue by xinix00** [Fmstrat/wintile#61]
If I want a screen 1 column larger (or one row higher) I now have to pres SUPER + UP, SUPER + UP (to make it maximized) SUPER + LEFT to make it 3 columns.

I would love to have SUPER + SHIFT + RIGHT/LEFT to make it from 2 columns to 3 columns (I use this on a super ultrawide screen with 4 columns). Also the same idea if you are 1 row 1 column in size, and you want it to span 2 rows, I now have to SUPER + UP (maximizes) SUPER + LEFT SUPER+ LEFT SUPER+LEFT instead of SUPER + SHIFT + UP/DOWN (depending on which position you are).

I can do this myself if you want, but shall I post it as a pull request?

**Comment by GrylledCheez** [comment]
Added `<Super>`+`<Ctrl>`+`<Arrow>` to grow if there's space
3700fa8d2bd2d00ae60b5ef439f963972690298f
