### ISSUE TITLE
Extension not compatible with GNOME 40.1.0

### ISSUE THREAD

**Issue by christianfl** [Fmstrat/wintile#64]
Hey! Thanks for this neat extension. Unfortunately the extensions.gnome.org site states "INCOMPATIBLE". Hence, installing is not possible over that page. I'm running Fedora 34 with GNOME 40.1.0.

**Comment by DaemonLife** [comment]
Great extension, what I have been looking for for a long time! but on gnome 40.2 it is also impossible to install from the site. Is manual installation possible? I hope this extension will be supported by the entire community!

**Comment by DaemonLife** [comment]
Use this command to disable shell version checking. 

`gsettings set org.gnome.shell disable-extension-version-validation "true"`

Refresh [page](https://extensions.gnome.org/extension/1723/wintile-windows-10-window-tiling-for-gnome/) and install the extension and enter next command:

`gsettings set org.gnome.shell disable-extension-version-validation "false"`

**Comment by JAKuhr** [comment]
The latest version should be compatible with Gnome 40. I think the problem is the entry for the "shell-version" in the file "metadata.json". Gnome 40 is listed as "40.0" but should be listed as "40" to include also 40.1, 40.2 and so on.
