### ISSUE TITLE
Wintile overrides GNOME 40 keyboard shortcut settings

### ISSUE THREAD

**Issue by TheRoarkster** [Fmstrat/wintile#67]
I really enjoyed wintile and appreciate your development of the extension.  Unfortunately, it kept overriding my GNOME settings for keyboard shortcuts (e.g., tile left 1/2, tile right 1/2).  I couldn't find a way to turn this off in the settings.  Though I don't use it anymore, I thought I'd report the issue.

**Comment by GrylledCheez** [comment]
In CentOS 7 and Ubuntu, the half-screen tile combo is `<SUPER>`+`<CTRL>`+`<SHIFT>`+`<LEFT or RIGHT>`.

I'm assuming it's in others as well.
