### ISSUE TITLE
gsettings: No schema found

### ISSUE THREAD

**Issue by hmlendea** [Fmstrat/wintile#68]
There's some issue with the gsettings of this app.
When using `dconf-editor` all of the settings have the following warning/error: `No schema found` and have no default value/description.

![image](https://user-images.githubusercontent.com/10261133/131340152-d2971d4a-5c4e-49a6-b9f0-052a53dfc74f.png)

They still get saved and loaded by the extension, but they are not implemented properly.

This also prevents setting them via command line / script, for example:
`gsettings set /org/gnome/shell/extensions/wintile/ use-minimize false`
will error out with
`No such schema “/org/gnome/shell/extensions/wintile/”`

While most might not encounter this, it's problematic for me since I use a script to keep my settings in sync across multiple computers.

**Comment by rsxchin** [comment]
If you want to install it systemwide, you can do this as root. 
`cp org.gnome.shell.extensions.wintile.gschema.xml /usr/share/glib-2.0/schemas/`
`cd /usr/share/glib-2.0/schemas/`
`glib-compile-schemas .`
