### ISSUE TITLE
Bump for GNOME 41    

### ISSUE THREAD

**Issue by okias** [Fmstrat/wintile#69]
Please bump version,  Debian testing just switched to GNOME 41 making this extension not usable.

**Comment by volodymyrkramar** [comment]
triple

**Comment by dhiller** [comment]
+100 since pop-shell fails on me and gtile is not working. Would be really great to see this!

**Comment by bshor** [comment]
Me too!

**Comment by fthiery** [comment]
Just adding 41.0 to the metadata.json file did the trick for me

```
{
    "name": "WinTile: Windows 10 window tiling for GNOME",
    "description": "WinTile is a hotkey driven window tiling system for GNOME that imitates the standard Win-Arrow keys of Windows 10, allowing you to maximize, maximize to sides, or 1/4 sized to corner across a single or multiple monitors using just Super+Arrow.\n\nAs of v3, WinTile also supports:\n- 2, 3, or 4 columns for standard or ultrawide monitors\n- Top/bottom half support\n- Mouse preview and snapping for placing windows\n- Toggling of 'maximize' mode, which adds/removes GNOME animations",
    "uuid": "wintile@nowsci.com",
    "url": "https://github.com/fmstrat/wintile",
    "shell-version": [
        "3.28",
        "3.30",
        "3.32",
        "3.34",
        "3.36",
        "3.38",
        "40.0",
        "41.0"
    ],
    "version": 7
}

```

**Comment by fthiery** [comment]
Apparently someone else did something already:
https://github.com/Fmstrat/wintile/pull/70

**Comment by ahodges22** [comment]
Any idea when a release will be created with that bump?

**Comment by nihil39** [comment]
Is it possible to make a fork release with just that version bump?

**Comment by bshor** [comment]
Where is the metadata.json file in the file system to modify for 41?

**Comment by okias** [comment]
Hey @Fmstrat while I'm very glad you made this extension, but have you thought about giving someone who could maintain it access to the repo?

On one hand, it's great extension, on other hand, until I manually bumped it to support GNOME 41, it kept me with half-broken window managment (broken shortcuts), so it would be nice to approach it somehow :wink:

**Comment by Fmstrat** [comment]
@okais

> Hey @Fmstrat while I'm very glad you made this extension, but have you thought about giving someone who could maintain it access to the repo?

I'd love to. @jacksongoode @justperfection @lamarios @wiebe as you've provided PRs for GNOME bumps, are any of you interested?

**Comment by lamarios** [comment]
I don't mind helping, but I still wouldn't have access to the gnome extension account to publish it.

**Comment by wiebe** [comment]
I also wouldn't mind helping, still use this extension everyday :-)

**Comment by Fmstrat** [comment]
@lamarios @wiebe Let me figure out how to handle extension submission, then I'll add you both. Thanks!

**Comment by Kerwood** [comment]
For the impatient, you can disable version validation with the following command.
```
gsettings set org.gnome.shell disable-extension-version-validation "true"
```

Set it to false to enable it again.

**Comment by okias** [comment]
@Fmstrat what is the current status (GNOME 43 made a reminder about this for me)? Thanks

**Comment by Kerwood** [comment]
It looks like the development of this fine extension has dies. Some have forked it. 
Have a look at https://github.com/Fmstrat/wintile/pull/82#issuecomment-1193095739
