### ISSUE TITLE
Please document this extension's functionality

### ISSUE THREAD

**Issue by sylvainfaivre** [Fmstrat/wintile#72]
Some people (like me) haven't used a Windows OS for years, but would be interested in this extension anyway.
How should we know what it does ?
As far as I could see by reading articles and trying it out :

- define a grid of 2 rows x 2 to 4 columns (tunable)
- send window to some place in that grid, either moving the window with your mouse, or using [Win + arrows] keyboard shortcuts

Is that all ? anything I missed ?
I am willing to write a doc PR if needed, but I'm not sure I got everything right :-)

**Comment by sylvainfaivre** [comment]
I guess this is explained, in part, on top of the README, but I mean it lacks the specifics.
Like this : 
- you can have a window fill one column using [Win + Left arrow] or [Win + Right arrow]
- then you can tile a window into a half column using [Win + Up arrow] or [Win + Down arrow]
- ...

**Comment by yeroc** [comment]
Agreed, I'm struggling to figure out this information as well.  There doesn't seem to be any way (via keyboard or mouse) that I've been able to find to get a window in the middle column on a 3 column layout?

**Comment by rsxchin** [comment]
Currently, the simplest way to fill the middle column is to drag down in the center and then use <Super>+up.

**Comment by rsxchin** [comment]
@yeroc, #110 allows you to drag in the center of any column to be full height in that column.

But yeah, we'll work on proper documentation soon.

**Comment by yeroc** [comment]
@GrylledCheez That's awesome, I might be able to switch back to this extension instead of gTile!

**Comment by GrylledCheez** [comment]
@yeroc, see how well the https://github.com/Fmstrat/wintile/tree/v10_candidate branch works for you? We're in the process of getting it approved.

**Comment by GrylledCheez** [comment]
@yeroc, are you still willing to rewrite the README?

**Comment by yeroc** [comment]
@GrylledCheez Unfortunately, I'm running AlmaLinux 8 so I believe I'm stuck back on v7.  I can take a look at the README.  It was @sylvainfaivre that had initially offered to look at it.

**Comment by GrylledCheez** [comment]
@yeroc, I see that I messaged the wrong person.
If v7 works for you, the latest versions will work too. It just isn't on extensions.gnome.org yet. 

To manually install the latest version:
1. `wget https://github.com/Fmstrat/wintile/releases/download/v10/wintile@nowsci.com.zip -O /tmp/`
2. `unzip ~/.local/share/gnome-shell/extensions/`
3. Press alt+f2
4. `r`

Let us know if you have any problems

**Comment by yeroc** [comment]
@GrylledCheez I've done some testing using <super>-left/right/up/down and things look fine to me.  I'm not sure I understand what's happening in all cases but it seems workable.  I would note that it doesn't interact well with the Window Focus set to Secondary-Click setting on Gnome 3.32 as focus switches windows sometimes as they're moved.  It would be great if a way could be found to ensure focus isn't lost so you can always reliably hit <super>-left (or whatever key) multiple times to move a single window.

**Comment by GrylledCheez** [comment]
What are you expecting to happen with secondary click?

Did you also get a chance to play with the ultrawide only mode, as well as
dragging along the bottom to spawn at full height?

**Comment by GrylledCheez** [comment]
@yeroc, I'm moving that to a new issue #119

**Comment by GrylledCheez** [comment]
I updated the README.md in b43f41b4ee1ec238a5c27b50ea32630960c28802. Let me know if there is anything I'm missing or that is unclear.
