### ISSUE TITLE
Since gnome-shell 41.3 window switch back to previous size when switching window

### ISSUE THREAD

**Issue by lamarios** [Fmstrat/wintile#74]
Fedora 35 on wayland

Let say i resize a window from 1/2 to 1/4 then if i switch to another window it will resize back to 1/2. I was looking around and saw that the gTile extension is also facing the same issue here: https://github.com/gTile/gTile/issues/267 

It might be worth to follow this thread to figure out the issue

**Comment by lamarios** [comment]
a bug was opened here: https://gitlab.gnome.org/GNOME/mutter/-/issues/2091

**Comment by GrylledCheez** [comment]
@lamarios, please reopen this if it's still an issue.
