### ISSUE TITLE
Modifiable columns width

### ISSUE THREAD

**Issue by martinhoyer** [Fmstrat/wintile#78]
As I understand, currently we can use n number of columns which will always be evenly divided.  
The idea is to add support for editing column(s) width.  
One use-case would be for ultra-wide monitor users, where it might be desirable to have 3 columns, with the centre one slightly wider then the side ones.

**Comment by rsxchin** [comment]
The current iteration has a centered 1/2 screen mode when using 4 columns that leaves 1/4 screen on either side.
