### ISSUE TITLE
visual glitch when maximalizing window

### ISSUE THREAD

**Issue by okias** [Fmstrat/wintile#79]
HW: 4k screen
SW: GNOME 41

Keypress:
- WINkey + UP arrow

What happends with wintile:
- window is moved in position 0,0 in current size
- window is maximallized

Without wintile:
- animation show fluent maximalization from current window size and position.

Log:
```
gnome-shell[1610]: [WinTile], mouse - x:2299 y:1639
gnome-shell[1610]: [WinTile], monitor - x:0 y:360 w:3200 h:1800 inB:true
gnome-shell[1610]: [WinTile], space - x:0 y:360 w:3200 h:1800
gnome-shell[1610]: [WinTile], window - x:1296 y:1588 w:1468 h:1050
gnome-shell[1610]: [WinTile], windowGrabEnd
gnome-shell[1610]: [WinTile], checkIfNearGrid
gnome-shell[1610]: [WinTile], initApp
gnome-shell[1610]: [WinTile], init as maximize
gnome-shell[1610]: [WinTile], windowGrabBegin
gnome-shell[1610]: [WinTile], windowGrabEnd
```

**Comment by GrylledCheez** [comment]
@okias, is this still an issue for you? I'll reopen it if it is.

If so, please provide your os and gnome versions.
