### ISSUE TITLE
Tiling with 4 columns causes out-of-screen on the right side

### ISSUE THREAD

**Issue by raphaelkerschbaumer** [Fmstrat/wintile#80]
I just downloaded WinTile and played around a bit with it. During that I found out, that when using 4 columns and moving windows to the rightmost quarter, some of them are moving partly out-of-screen (the "x" in the upper right corner of the window isn't visible anymore). This does not happen with all applications though, however, I've experienced it on these:
- Google Chrome
- Ubuntu Settings 
- Gnome Tweak Tools 

However, I couldn't see it when using the Terminal. I think the root cause may be the min-settings for some application-window-sizes. 

Is this something that can be fixed? The only thing I can think of is, that when aligning a window on the rightmost corner(s), it should be aligned with the right border of the screen, and not with the column-lines previously configured. However, this would also mean that said windows are most likely overlapping with other windows who are aligned properly.

Maybe someone who has more knowledge about how window-scaling actually works can think of a solution to this.  

OS: Ubuntu 20.04
Screen resolution: 1920x1080

**Comment by rsxchin** [comment]
Confirmed.  What's odd is that it only affects 1920x1080 monitors if they're on the left.

**Comment by rsxchin** [comment]
fixed in #113
