### ISSUE TITLE
GNOME 42

### ISSUE THREAD

**Issue by mdfahner** [Fmstrat/wintile#81]
With GNOME 42 out, it would be great to have the extension support it.  Is anything needed to be changed aside from adding 42 to the metadata?

**Comment by mdfahner** [comment]
https://github.com/Fmstrat/wintile/pull/82

**Comment by joseph-zhong** [comment]
Thanks @mdfahner -- Tested it on a fairly fresh install of Ubuntu 22.04 / GnomeShell 42 and works like a charm!

**Comment by MatthiasLohr** [comment]
@Fmstrat, any chance to get this supported?

**Comment by phavekes** [comment]
This is solved by #88, waiting for a new release.
