### ISSUE TITLE
GNOME 43

### ISSUE THREAD

**Issue by charlesritchea** [Fmstrat/wintile#89]
Gnome 43 comes with Ubuntu 22.10 and wintile yet again is disabled. Seeing as this happens every release of Gnome, maybe there is a different approach to setting version support?

**Comment by gregorgr** [comment]
I managed to make it work in GNOME 43 and the solution is pretty simple.
find file **metadata.json** in directory:
/home/user/.local/share/gnome-shell/extensions/wintile@nowsci.com 
and change content to:
{
    "name": "WinTile: Windows 10 window tiling for GNOME",
    "description": "WinTile is a hotkey driven window tiling system for GNOME that imitates the standard Win-Arrow keys of Windows 10, allowing you to maximize, maximize to sides, or 1/4 sized to corner across a single or multiple monitors using just Super+Arrow.\n\nAs of v3, WinTile also supports:\n- 2, 3, or 4 columns for standard or ultrawide monitors\n- Top/bottom half support\n- Mouse preview and snapping for placing windows\n- Toggling of 'maximize' mode, which adds/removes GNOME animations",
    "uuid": "wintile@nowsci.com",
    "url": "https://github.com/fmstrat/wintile",
    "session-modes":   "user" ,

    "shell-version": [
        "3.28",
        "3.30",
        "3.32",
        "3.34",
        "3.36",
        "3.38",
        "40",
        "41",
        "42",
        "43'"
    ],
    "version": 7.010
}

So what is different:
I added (gmome 43) line :
    "session-modes":   "user" ,
updated suported versions to:
    "shell-version": [
        "3.28",
        "3.30",
        "3.32",
        "3.34",
        "3.36",
        "3.38",
        "40",
        "41",
        "42",
        "43'"
    ],
    and changed version of extension aka:
    "version": 7.010

**Comment by phavekes** [comment]
This is solved by #88, waiting for a new release.
