### ISSUE TITLE
Please enable for Ubuntu 22.04

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [Fmstrat/wintile#91]
Currently it won't install on Ubuntu 22.04 which has `GNOME Shell 42.5`: [How can I snap a window in a corner in Ubuntu 22.04?](https://askubuntu.com/q/1446384/327339)

**Comment by ElectricRCAircraftGuy** [comment]
Related: https://github.com/Fmstrat/wintile/issues/81

**Comment by ElectricRCAircraftGuy** [comment]
I just added detailed WinTile Reloaded installation instructions here: [How can I automatically resize a window to 1/4 of the screen and snap it to a corner in Ubuntu 22.04?](https://askubuntu.com/a/1446690/327339)

**Comment by gourcetools** [comment]
Much needed. thanks

**Comment by phavekes** [comment]
This is solved by #88, waiting for a new release.
