### ISSUE TITLE
[BUG] Windows jump when resizing

### ISSUE THREAD

**Issue by rsxchin** [Fmstrat/wintile#97]
1. open an application
2. snap it to any predefined wintile area
3. try to resize from any corner/edge
4. watch the window jump oddly

Expected behavior is that height or width be maintained depending on if x or y is changing.

[Screencast from 2023-04-25 10-59-27.webm](https://user-images.githubusercontent.com/3096423/234227678-d791943d-3c83-42f4-8e3a-0fefb52e395b.webm)

**Comment by SteamWind** [comment]
Resizing should not trigger Wintile in my opinion...
