### ISSUE TITLE
Publish to GNOME Extensions

### ISSUE THREAD

**Issue by JanPokorny** [Fmstrat/wintile#99]
GNOME Extensions website has an older version of this extension. Not only does this make it less discoverable that GNOME 44 is actually supported, but somehow for me it kept "updating" to the older version even though I manually installed the new one. (I had to hard-code the version string so it matches to fix it.)

Please publish to the GNOME Extensions website, thank you!

**Comment by Fmstrat** [comment]
The only reason this hasn't happened is there are some updates the GNOME team are requiring to remove deprecation. I have it on the TODO list, but haven't been able to get to it yet, unfortunately.

**Comment by rsxchin** [comment]
What's on the list? Maybe we can help whittle it down.

**Comment by Fmstrat** [comment]
Closing due to specifics in https://github.com/Fmstrat/wintile/issues/102
